const fs = require("fs");
const path = require("path");

const phrasesFilePath = path.join(__dirname, "../src/translations/universalPhrases.ts");

const CAT1_PHRASES = {
  "Cross-border expansion commonly stalls when disconnected service providers drop the ball. ARSSA integrates the full value chain to protect your capital and accelerate your timeline.": {
    en: "Cross-border expansion commonly stalls when disconnected service providers drop the ball. ARSSA integrates the full value chain to protect your capital and accelerate your timeline.",
    fr: "L'expansion transfrontalière s'arrête souvent lorsque des prestataires déconnectés échouent. ARSSA intègre toute la chaîne de valeur pour protéger votre capital et accélérer votre calendrier.",
    pt: "A expansão transfronteiriça frequentemente falha quando prestadores desconectados cometem erros. A ARSSA integra toda a cadeia de valor para proteger o seu capital e acelerar o seu cronograma.",
    sw: "Upanuzi wa mipakani mara nyingi hukwama wakati watoa huduma wasiowasiliana wanaposhindwa. ARSSA inajumuisha mnyororo mzima wa thamani ili kulinda mtaji wako na kuharakisha ratiba yako.",
    ln: "Bokoli ya kokata bandelo ekangamaka mingi tango basali misala oyo bayebani te babebisi makambo. ARSSA esangisi banzela nyonso mpo na kobatela mbongo na yo mpe kosala noki.",
    af: "Oorgrensuitbreiding loop dikwels vas wanneer ongekoppelde diensverskaffers foute maak. ARSSA integreer die hele waardeketting om u kapitaal te beskerm en u tydlyn te versnel.",
    zu: "Ukwandiswa kwemingcele kuvame ukubambezeleka lapho abahlinzeki bezinsizakalo abangaxhumene behluleka. I-ARSSA ihlanganisa lonke uchungechunge lwenani ukuze ivikele imali yakho futhi isheshise isikhathi sakho.",
    xh: "Ukwandiswa kwemida kuhlala kuthinteka xa ababoneleli beenkonzo abangaqhagamshelwanga besilela. I-ARSSA idibanisa lonke uthungelwano lwexabiso ukukhusela inkunzi yakho nokukhawulezisa ixesha lakho.",
    zh: "跨国业务拓展往往因各个孤立的服务中介互相推诿而陷入停滞。ARSSA 整合全产业链条，切实保障您的投资资本并大幅加快落地推进节奏。",
    ar: "غالباً ما يتوقف التوسع عبر الحدود عندما يقصر مقدمو الخدمات المنفصلون. تجمع ARSSA بين سلسلة القيمة بأكملها لحماية رأس مالك وتسريع جدولك الزمني.",
    es: "La expansión transfronteriza a menudo se estanca cuando proveedores desconectados fallan. ARSSA integra toda la cadena de valor para proteger su capital y acelerar sus tiempos.",
    de: "Grenzüberschreitende Expansion stockt häufig, wenn unkoordinierte Dienstleister versagen. ARSSA integriert die gesamte Wertschöpfungskette, um Ihr Kapital zu sichern und Ihren Zeitplan zu beschleunigen.",
    hi: "सीमा पार विस्तार आमतौर पर तब रुक जाता है जब असंबद्ध सेवा प्रदाता विफल हो जाते हैं। ARSSA आपकी पूंजी की रक्षा करने और आपकी समयसीमा को तेज करने के लिए संपूर्ण मूल्य श्रृंखला को एकीकृत करता है।",
    ru: "Трансграничная экспансия часто буксует из-за несогласованности разрозненных подрядчиков. ARSSA объединяет всю цепочку создания стоимости, защищая ваш капитал и ускоряя график запуска.",
    ja: "国境を越えた事業拡大は、分断された外部業者の連携不足によって停滞しがちです。ARSSA はバリューチェーン全体を統合し、貴社の投資資本を保護しながらスケジュールを加速させます。",
    ko: "국경 간 확장은 연계되지 않은 개별 서비스 제공업체들이 실책을 범할 때 정체되기 쉽습니다. ARSSA는 가치 사슬 전체를 통합하여 귀사의 자본을 보호하고 일정을 단축합니다.",
    it: "L'espansione transfrontaliera spesso si arena quando fornitori disconnessi falliscono. ARSSA integra l'intera catena del valore per proteggere il tuo capitale e accelerare i tempi.",
    nl: "Grensoverschrijdende expansie loopt vaak vertraging op wanneer niet-verbonden dienstverleners steken laten vallen. ARSSA integreert de volledige waardeketen om uw kapitaal te beschermen en uw planning te versnellen.",
  },
  "Each division can be deployed individually or combined into an end-to-end operational roadmap.": {
    en: "Each division can be deployed individually or combined into an end-to-end operational roadmap.",
    fr: "Chaque division peut être déployée individuellement ou combinée dans une feuille de route opérationnelle de bout en bout.",
    pt: "Cada divisão pode ser implementada individualmente ou combinada num roteiro operacional de ponta a ponta.",
    sw: "Kila kitengo kinaweza kutumika kikiwa peke yake au kuunganishwa kuwa ramani kamili ya kiutendaji ya mwanzo hadi mwisho.",
    ln: "Eteni nyonso ya mosala ekoki kosalelama yango moko to kosangisama na ebongiseli mobimba ya mosala banda ebandeli kino suka.",
    af: "Elke afdeling kan individueel ontplooi word of gekombineer word in 'n end-tot-end operasionele padkaart.",
    zu: "Uphiko ngalunye lungasetshenziswa ngokuzimela noma luhlanganiswe lube uhlelo lokusebenza oluphelele kusukela ekuqaleni kuya ekugcineni.",
    xh: "Icandelo ngalinye linokusetyenziswa ngokukodwa okanye lidityaniswe kwisicwangciso sokusebenza esipheleleyo ukusuka ekuqaleni kuye ekugqibeleni.",
    zh: "各个业务部门既可独立承接专项委托，亦可协同组合为一体化端到端全流程运营路线图。",
    ar: "يمكن تفعيل كل قسم على حدة أو دمجه في خارطة طريق تشغيلية شاملة من البداية إلى النهاية.",
    es: "Cada división se puede implementar individualmente o combinar en una hoja de ruta operativa integral.",
    de: "Jeder Geschäftsbereich kann einzeln beauftragt oder zu einem durchgängigen operativen Fahrplan kombiniert werden.",
    hi: "प्रत्येक प्रभाग को व्यक्तिगत रूप से तैनात किया जा सकता है या एंड-टू-एंड परिचालन रोडमैप में जोड़ा जा सकता है।",
    ru: "Каждое подразделение может привлекаться отдельно либо в рамках единой комплексной дорожной карты «под ключ».",
    ja: "各事業部門は個別に活用することも、エンドツーエンドの包括的な運用ロードマップとして統合することも可能です。",
    ko: "각 부문은 개별적으로 활용하거나 엔드투엔드(End-to-End) 운영 로드맵으로 결합하여 유기적으로 진행할 수 있습니다.",
    it: "Ogni divisione può essere impiegata singolarmente o combinata in una tabella di marcia operativa end-to-end.",
    nl: "Elke divisie kan afzonderlijk worden ingezet of worden gecombineerd in een end-to-end operationeel stappenplan.",
  },
  "Corridor Execution": {
    en: "Corridor Execution",
    fr: "Exécution sur le Corridor",
    pt: "Execução no Corredor",
    sw: "Utekelezaji wa Korido",
    ln: "Bosali Mosala na Nzela ya Corridor",
    af: "Korridor-uitvoering",
    zu: "Ukwenziwa Kwephasishi",
    xh: "Ukwenziwa Komsebenzi Wephasishi",
    zh: "走廊经贸闭环执行",
    ar: "التنفيذ عبر ممر التجارة",
    es: "Ejecución en el Corredor",
    de: "Korridor-Abwicklung",
    hi: "गलियारा निष्पादन",
    ru: "Исполнение в торговом коридоре",
    ja: "回廊ビジネスの実行",
    ko: "회랑 비즈니스 실행",
    it: "Esecuzione lungo il Corridoio",
    nl: "Corridor-uitvoering",
  },
  "From Port to Distribution": {
    en: "From Port to Distribution",
    fr: "Du Port à la Distribution",
    pt: "Do Porto à Distribuição",
    sw: "Kutoka Bandarini hadi Usambazaji",
    ln: "Banda na Libongo kino na Bokabi Biloko",
    af: "Van Hawe tot Verspreiding",
    zu: "Kusuka Echwebeni kuya Ekusabalaliseni",
    xh: "Ukusuka eZibukweni kuye eKusasazeni",
    zh: "从出入境港口到终端商超分销",
    ar: "من الميناء إلى شبكات التوزيع",
    es: "Del Puerto a la Distribución",
    de: "Vom Hafen bis zum Endvertrieb",
    hi: "बंदरगाह से वितरण तक",
    ru: "От морского порта до конечной дистрибуции",
    ja: "港湾到着から店舗流通・店頭配荷まで",
    ko: "항만 통관부터 최종 유통망 입점까지",
    it: "Dal Porto alla Distribuzione",
    nl: "Van Haven tot Distributie",
  },
  "Comprehensive compliance, freight coordination, and last-mile placement in the DRC.": {
    en: "Comprehensive compliance, freight coordination, and last-mile placement in the DRC.",
    fr: "Conformité complète, coordination du fret et placement du dernier kilomètre en RDC.",
    pt: "Conformidade abrangente, coordenação de frete e colocação na última milha na RDC.",
    sw: "Uzingatiaji kamili wa sheria, uratibu wa mizigo, na usambazaji wa hatua ya mwisho nchini DRC.",
    ln: "Botosi ya mibeko mobimba, kotambwisa biloko na motuka to mpepo mpe kotiya yango na maboko ya basombi na RDC.",
    af: "Omvattende voldoening, vragkoördinasie en laaste-myl-plasing in die DRK.",
    zu: "Ukuhambisana okuphelele nomthetho, ukuxhumanisa impahla, nokubekwa kwebanga lokugcina e-DRC.",
    xh: "Ukuthotyelwa okubanzi, ulungelelaniso lwezothutho, nokufakwa kwemayile yokugqibela e-DRC.",
    zh: "覆盖刚果（金）全境的法规合规审批、跨国干线多式联运及最后一公里终端配货。",
    ar: "امتثال شامل، وتنسيق للشحن، وتوزيع في الميل الأخير داخل جمهورية الكونغو الديمقراطية.",
    es: "Cumplimiento integral, coordinación de fletes y colocación de última milla en la RDC.",
    de: "Umfassende Compliance, Frachtkoordination und Last-Mile-Platzierung in der DR Kongo.",
    hi: "डीआरसी में व्यापक अनुपालन, माल ढुलाई समन्वय और अंतिम-मील प्लेसमेंट।",
    ru: "Полный комплаенс, экспедирование грузов и дистрибуция «последней мили» в ДРК.",
    ja: "コンゴ民主共和国における包括的コンプライアンス、貨物輸送調整、ラストワンマイルの店頭配荷。",
    ko: "콩고민주공화국 전역에 걸친 종합 규정 준수, 화물 운송 조율 및 라스트마일 현장 입점.",
    it: "Conformità completa, coordinamento delle merci e posizionamento dell'ultimo miglio nella RDC.",
    nl: "Uitgebreide compliance, vrachtcoördinatie en last-mile schapplaatsing in de DRC.",
  },
  "We tailor each division's execution to the regulatory frameworks, channel structures, and storage requirements of your specific product vertical.": {
    en: "We tailor each division's execution to the regulatory frameworks, channel structures, and storage requirements of your specific product vertical.",
    fr: "Nous adaptons l'exécution de chaque division aux cadres réglementaires, aux structures de canaux et aux exigences de stockage de votre secteur de produits spécifique.",
    pt: "Adaptamos a execução de cada divisão aos quadros regulamentares, estruturas de canais e requisitos de armazenamento do seu sector de produtos específico.",
    sw: "Tunarekebisha utekelezaji wa kila kitengo kulingana na mifumo ya udhibiti, miundo ya njia za mauzo na mahitaji ya uhifadhi ya bidhaa zako mahususi.",
    ln: "Tobongisaka mosala ya biteni nyonso na kotalela mibeko ya leta, ndenge ya koteka mpe bisika ya kobomba biloko na yo ya sikisiki.",
    af: "Ons pas elke afdeling se uitvoering aan by die regulatoriese raamwerke, kanaalstrukture en bergingsvereistes van u spesifieke produkvertikaal.",
    zu: "Senza ngezifiso ukwenziwa kophiko ngalunye ngokwezinhlaka zokulawula, izakhiwo zeziteshi, nezidingo zokugcina zomkhiqizo wakho othile.",
    xh: "Silungelelanisa ukwenziwa kwecandelo ngalinye kwizikhokelo zolawulo, izakhiwo zamajelo, neemfuno zokugcina imveliso yakho ethile.",
    zh: "针对您特定垂直品类的法规政策框架、商超批发渠道特点及特殊温控仓储要求，量身定制各大业务部门的执行方案。",
    ar: "نقوم بتخصيص تنفيذ كل قسم وفقاً للأطر التنظيمية وهياكل القنوات ومتطلبات التخزين الخاصة بفئة منتجاتك المحددة.",
    es: "Adaptamos la ejecución de cada división a los marcos regulatorios, estructuras de canales y requisitos de almacenamiento de su vertical de productos específica.",
    de: "Wir passen die Ausführung jedes Geschäftsbereichs an die regulatorischen Rahmenbedingungen, Vertriebsstrukturen und Lageranforderungen Ihrer spezifischen Produktkategorie an.",
    hi: "हम प्रत्येक प्रभाग के निष्पादन को आपके विशिष्ट उत्पाद क्षेत्र के विनियामक ढांचे, चैनल संरचनाओं और भंडारण आवश्यकताओं के अनुसार तैयार करते हैं।",
    ru: "Мы адаптируем работу каждого подразделения под нормативную базу, структуру сбыта и требования к хранению вашей конкретной продуктовой категории.",
    ja: "貴社固有の製品カテゴリーに応じた法規制フレームワーク、流通チャネル構造、保管要件に合わせて各事業部門の実行プランを最適化します。",
    ko: "귀사 제품 카테고리의 규제 체계, 유통 채널 구조 및 보관 요구조건에 맞추어 각 사업 부문의 실행 방식을 정밀하게 맞춤화합니다.",
    it: "Adattiamo l'esecuzione di ogni divisione ai quadri normativi, alle strutture di canale e ai requisiti di stoccaggio della tua specifica categoria di prodotto.",
    nl: "We stemmen de uitvoering van elke divisie af op de wettelijke kaders, kanaalstructuren en opslagvereisten van uw specifieke productcategorie.",
  },
  "Agri-Food & Agricultural Inputs": {
    en: "Agri-Food & Agricultural Inputs",
    fr: "Agroalimentaire et Intrants Agricoles",
    pt: "Agroalimentar e Insumos Agrícolas",
    sw: "Kilimo-Chakula na Pembejeo za Kilimo",
    ln: "Bilei mpe Biloko ya Mosala Bilanga",
    af: "Landbouvoedsel en Landbou-insette",
    zu: "Ukudla Kwezolimo Nezinto Ezisetshenziswa Kwezolimo",
    xh: "Ukutya Kwezolimo Nezixhobo Zezolimo",
    zh: "农副食品与农业生产资料",
    ar: "المنتجات الغذائية الزراعية والمدخلات الزراعية",
    es: "Agroalimentario e Insumos Agrícolas",
    de: "Agrar- & Lebensmittel und landwirtschaftliche Betriebsmittel",
    hi: "कृषि-खाद्य और कृषि इनपुट",
    ru: "Агропродовольственная продукция и сельхозсырье",
    ja: "農産食品および農業資材",
    ko: "농식품 및 농업 자재",
    it: "Agroalimentare e Forniture Agricole",
    nl: "Agro-food & Landbouwinputs",
  },
  "Each client segment faces unique regulatory, logistical, and commercial hurdles. Our five divisions coordinate to provide the exact solution needed.": {
    en: "Each client segment faces unique regulatory, logistical, and commercial hurdles. Our five divisions coordinate to provide the exact solution needed.",
    fr: "Chaque segment de clientèle est confronté à des obstacles réglementaires, logistiques et commerciaux uniques. Nos cinq divisions se coordonnent pour fournir la solution exacte requise.",
    pt: "Cada segmento de clientes enfrenta obstáculos regulamentares, logísticos e comerciais únicos. As nossas cinco divisões coordenam-se para fornecer a solução exacta necessária.",
    sw: "Kila kundi la wateja linakabiliwa na vikwazo vya kipekee vya kikanuni, vifaa na kibiashara. Vitengo vyetu vitano vinaratibiwa kutoa suluhisho sahihi linalohitajika.",
    ln: "Kila eteni ya bakompani ekutanaka na mikakatano ya mibeko, ya kotambwisa biloko mpe ya mombo. Biteni na biso mitano esanganaka mpo na kopesa eyano ya sikisiki oyo esengeli.",
    af: "Elke kliëntesegment staar unieke regulatoriese, logistieke en kommersiële struikelblokke in die gesig. Ons vyf afdelings koördineer om die presiese oplossing te bied wat benodig word.",
    zu: "Ingxenye ngayinye yamakhasimende ibhekene nezithiyo ezihlukile zokulawula, ezokuthutha, nezohwebo. Izigaba zethu ezinhlanu zisebenza ndawonye ukuhlinzeka ngesixazululo esiqondile esidingekayo.",
    xh: "Icandelo ngalinye labathengi lijongene nemiqobo ekhethekileyo yolawulo, ezolungiselelo, nezorhwebo. Amacandelo ethu amahlanu alungelelanisa ukubonelela ngesisombululo esichanekileyo esifunekayo.",
    zh: "各类客户群体均面临其独有的政策法规、跨境物流与商业渠道壁垒。我们的五大业务部门协同配合，提供精准契合的专属解决方案。",
    ar: "يواجه كل قطاع من العملاء عقبات تنظيمية ولوجستية وتجارية فريدة. تنسق أقسامنا الخمسة لتقديم الحل الدقيق المطلوب.",
    es: "Cada segmento de clientes enfrenta obstáculos regulatorios, logísticos y comerciales únicos. Nuestras cinco divisiones se coordinan para brindar la solución exacta requerida.",
    de: "Jedes Kundensegment steht vor individuellen regulatorischen, logistischen und kommerziellen Hürden. Unsere fünf Geschäftsbereiche koordinieren sich, um die exakt passende Lösung zu liefern.",
    hi: "प्रत्येक ग्राहक वर्ग अद्वितीय नियामक, तार्किक और वाणिज्यिक बाधाओं का सामना करता है। हमारे पांच प्रभाग आवश्यक सटीक समाधान प्रदान करने के लिए समन्वय करते हैं।",
    ru: "Каждый сегмент клиентов сталкивается со своими регуляторными, логистическими и коммерческими вызовами. Наши пять подразделений действуют согласованно, формируя точно выверенное решение.",
    ja: "顧客セグメントごとに異なる法規制、物流、商習慣上の課題が存在します。当社の5大事業部門が緊密に連携し、まさに必要とされる的確なソリューションを提供します。",
    ko: "고객 부문마다 고유한 규제, 물류 및 상업적 장벽에 직면합니다. 당사의 5대 사업 부문이 긴밀히 협력하여 정확히 필요한 맞춤형 솔루션을 제공합니다.",
    it: "Ogni segmento di clienti affronta ostacoli normativi, logistici e commerciali unici. Le nostre cinque divisioni si coordinano per fornire l'esatta soluzione necessaria.",
    nl: "Elk klantsegment heeft te maken met unieke regelgevende, logistieke en commerciële drempels. Onze vijf divisies werken samen om precies de gewenste oplossing te bieden.",
  },
  "ARSSA acts as the single accountable bridge between where your business originates and where it creates commercial impact.": {
    en: "ARSSA acts as the single accountable bridge between where your business originates and where it creates commercial impact.",
    fr: "ARSSA agit comme le pont unique et responsable entre le lieu d'origine de votre entreprise et celui où elle crée un impact commercial.",
    pt: "A ARSSA actua como a ponte única e responsável entre onde o seu negócio tem origem e onde cria impacto comercial.",
    sw: "ARSSA inafanya kazi kama daraja moja linalowajibika kati ya mahali biashara yako inapoanzia na mahali inapounda matokeo ya kibiashara.",
    ln: "ARSSA ezali gbagba moko kaka ya kotyela motema kati na esika mombo na yo ebandi mpe esika ekosala matomba ya solosolo.",
    af: "ARSSA tree op as die enkele verantwoordbare brug tussen waar u besigheid ontstaan en waar dit kommersiële impak skep.",
    zu: "I-ARSSA isebenza njengebhuloho elilodwa elibophezelekile phakathi kwalapho ibhizinisi lakho liqala khona nalapho lidala khona umthelela wezohwebo.",
    xh: "I-ARSSA isebenza njengebhulorho enye enoxanduva phakathi kwalapho ishishini lakho liqala khona nalapho lidala khona impembelelo yezorhwebo.",
    zh: "ARSSA 始终扮演单一负责任的战略桥梁，连通您企业战略发起的大本营与在刚果（金）创造商业盈利价值的核心阵地。",
    ar: "تعمل ARSSA كجسر موثوق ومسؤول يربط بين مقر انطلاق عملك ومكان تحقيقه للأثر التجاري والربحي.",
    es: "ARSSA actúa como el único puente responsable entre el origen de su negocio y el lugar donde genera impacto comercial.",
    de: "ARSSA fungiert als verlässliche, zentrale Brücke zwischen dem Ursprung Ihres Unternehmens und dem Ort, an dem es kommerzielle Wirkung entfaltet.",
    hi: "ARSSA एक एकल जवाबदेह पुल के रूप में कार्य करता है जहाँ से आपका व्यवसाय शुरू होता है और जहाँ यह वाणिज्यिक प्रभाव पैदा करता है।",
    ru: "ARSSA выступает надежным единым мостом между базой вашего бизнеса и рынком, на котором он генерирует коммерческий результат.",
    ja: "ARSSA は、貴社の事業発祥拠点と、実質的な商業成果を生み出す現地市場とをつなぐ、唯一の責任ある架け桥として機能します。",
    ko: "ARSSA는 귀사의 사업이 시작되는 거점과 실질적인 상업적 성과를 창출하는 시장 사이를 잇는 단 하나의 책임 있는 가교 역할을 수행합니다.",
    it: "ARSSA funge da unico ponte responsabile tra il luogo di origine della tua attività e quello in cui crea impatto commerciale.",
    nl: "ARSSA fungeert als de centrale, aansprakelijke brug tussen de thuisbasis van uw bedrijf en de markt waar u commerciële impact creëert.",
  },
  "Core Advantages": {
    en: "Core Advantages",
    fr: "Avantages Clés",
    pt: "Vantagens Principais",
    sw: "Manufaa Muhimu",
    ln: "Matomba ya Ntina",
    af: "Kernvoordele",
    zu: "Izinzuzo Eziyinhloko",
    xh: "Iinzuzo Ezingundoqo",
    zh: "核心竞争优势",
    ar: "المزايا الأساسية",
    es: "Ventajas Principales",
    de: "Zentrale Vorteile",
    hi: "प्रमुख लाभ",
    ru: "Ключевые преимущества",
    ja: "主な強み・選ばれる理由",
    ko: "핵심 강점 및 차별화 요소",
    it: "Vantaggi Chiave",
    nl: "Belangrijkste Voordelen",
  },
  "Important Context Regarding This Track Record": {
    en: "Important Context Regarding This Track Record",
    fr: "Contexte Important Concernant ces Réalisations",
    pt: "Contexto Importante Sobre Este Histórico",
    sw: "Muktadha Muhimu Kuhusu Rekodi Hii ya Mafanikio",
    ln: "Makambo ya Ntina mpo na Misala oyo Esalema",
    af: "Belangrike Konteks Omtrent Hierdie Baanrekord",
    zu: "Ingqikithi Ebalulekile Mayelana Nalo Mlando Womsebenzi",
    xh: "Umxholo Obalulekileyo Malunga Nale Rekhodi Yomsebenzi",
    zh: "关于过往履约业绩的重要声明与背景说明",
    ar: "سياق هام بشأن هذا السجل الحافل من الإنجازات",
    es: "Contexto Importante Sobre este Historial de Proyectos",
    de: "Wichtiger Kontext zu dieser Erfolgsbilanz",
    hi: "इस ट्रैक रिकॉर्ड के संबंध में महत्वपूर्ण संदर्भ",
    ru: "Важная информация об опыте реализации проектов",
    ja: "過去のプロジェクト実績に関する重要なお知らせ",
    ko: "당사의 프로젝트 실적에 관한 주요 배경 안내",
    it: "Contesto Importante Riguardo a Questo Storico",
    nl: "Belangrijke Context Betreffende Deze Ervaring",
  },
  "The historical projects showcased below reflect the ARS Group legacy and partnership experience in the DRC — rather than claiming every historical project was directly undertaken by ARSSA as a South African (SADAC) entity. This track record underpins the operational capability, sector knowledge, and corporate relationships that ARSSA brings to South African (SADAC) clients today.": {
    en: "The historical projects showcased below reflect the ARS Group legacy and partnership experience in the DRC — rather than claiming every historical project was directly undertaken by ARSSA as a South African (SADAC) entity. This track record underpins the operational capability, sector knowledge, and corporate relationships that ARSSA brings to South African (SADAC) clients today.",
    fr: "Les projets historiques présentés ci-dessous reflètent l'héritage et l'expérience de partenariat du Groupe ARS en RDC — sans prétendre que chaque projet historique a été directement entrepris par ARSSA en tant qu'entité sud-africaine (SADAC). Ce bilan sous-tend la capacité opérationnelle, la connaissance sectorielle et les relations d'affaires qu'ARSSA met aujourd'hui au service de ses clients sud-africains (SADAC).",
    pt: "Os projectos históricos apresentados abaixo reflectem o legado e a experiência de parceria do Grupo ARS na RDC — em vez de afirmar que cada projecto histórico foi realizado directamente pela ARSSA como entidade sul-africana (SADAC). Este histórico sustenta a capacidade operacional, o conhecimento do sector e as relações corporativas que a ARSSA oferece hoje aos clientes sul-africanos (SADAC).",
    sw: "Miradi ya kihistoria iliyoonyeshwa hapa chini inaakisi urithi na uzoefu wa ushirikiano wa Kikundi cha ARS nchini DRC — badala ya kudai kuwa kila mradi wa kihistoria ulifanywa moja kwa moja na ARSSA kama chombo cha Afrika Kusini (SADAC). Rekodi hii inaimarisha uwezo wa kiutendaji, ujuzi wa sekta na uhusiano wa kibiashara ambao ARSSA huleta kwa wateja wa Afrika Kusini (SADAC) leo.",
    ln: "Misala ya kala oyo elakisami awa ezali komonisa mayele mpe bokoli ya Groupe ARS na RDC — kasi te koloba ete misala nyonso esalemaki kaka na ARSSA lokola kompani ya Afríka ya Súdi (SADAC). Makambo oyo etongami na makoki ya solo ya mosala, boyebi ya bisika ya mosala mpe boyokani na bakompani oyo ARSSA ememeli bakompani ya Afríka ya Súdi (SADAC) lelo.",
    af: "Die historiese projekte wat hieronder vertoon word, weerspieël die ARS Groep-nalatenskap en vennootskapservaring in die DRK — eerder as om te beweer dat elke historiese projek direk deur ARSSA as 'n Suid-Afrikaanse (SADAC) entiteit onderneem is. Hierdie baanrekord onderskryf die operasionele vermoë, sektorkennis en korporatiewe verhoudings wat ARSSA vandag aan Suid-Afrikaanse (SADAC) kliënte bied.",
    zu: "Amaphrojekthi omlando aboniswe ngezansi abonisa ifa le-ARS Group nolwazi lokubambisana e-DRC — kunokuba kushiwo ukuthi wonke amaphrojekthi omlando enziwa ngokuqondile yi-ARSSA njengebhizinisi laseNingizimu Afrika (SADAC). Lo mlando wesipiliyoni usekela amandla okusebenza, ulwazi lomkhakha, nobudlelwano bezinkampani i-ARSSA ebulethela amakhasimende aseNingizimu Afrika (SADAC) namuhla.",
    xh: "Iiprojekthi zembali eziboniswe ngezantsi zibonisa ilifa leQela le-ARS namava obambiswano e-DRC — endaweni yokubanga ukuba yonke iprojekthi yembali yenziwe ngokuthe ngqo yi-ARSSA njengequmrhu laseMzantsi Afrika (SADAC). Le rekhodi yomsebenzi ixhasa amandla okusebenza, ulwazi lwecandelo, nobudlelwane benkampani obuziswa yi-ARSSA kubathengi baseMzantsi Afrika (SADAC) namhlanje.",
    zh: "以下展示的代表性历史业绩凝聚了 ARS 集团深耕刚果（金）多年的丰厚经验与政商合作网络 —— 并非指由南非实体 ARSSA 独自单独签约执行。正是这一扎实的历史积淀，构成了 ARSSA 今日为南非及 SADC 广大企业客户所提供的实操落地实力、专业垂直行业洞察与高端伙伴资源的核心基石。",
    ar: "تعكس المشاريع التاريخية المعروضة أدناه إرث مجموعة ARS وخبراتها في إقامة الشراكات داخل جمهورية الكونغو الديمقراطية — بدلاً من الادعاء بأن كل مشروع تاريخي تم تنفيذه مباشرة بواسطة ARSSA ككيان من جنوب أفريقيا (SADAC). يدعم هذا السجل الحافل القدرة التشغيلية والمعرفة بالقطاع والعلاقات المؤسسية التي تقدمها ARSSA لعملاء جنوب أفريقيا (SADAC) اليوم.",
    es: "Los proyectos históricos que se muestran a continuación reflejan el legado y la experiencia de asociación del Grupo ARS en la RDC, en lugar de afirmar que cada proyecto histórico fue realizado directamente por ARSSA como entidad sudafricana (SADAC). Este historial respalda la capacidad operativa, el conocimiento sectorial y las relaciones corporativas que ARSSA aporta a los clientes sudafricanos (SADAC) en la actualidad.",
    de: "Die unten dargestellten historischen Projekte spiegeln die Erfahrung und das Partnerschaftsnetzwerk der ARS-Gruppe in der DR Kongo wider — ohne den Anspruch zu erheben, dass jedes einzelne Projekt direkt von ARSSA als südafrikanischer (SADAC) Einheit durchgeführt wurde. Diese Erfolgsbilanz bildet das Fundament für die operative Leistungsfähigkeit, das Branchenwissen und die Geschäftsbeziehungen, die ARSSA südafrikanischen (SADAC) Kunden heute bietet.",
    hi: "नीचे दिखाए गए ऐतिहासिक प्रोजेक्ट डीआरसी में एआरएस ग्रुप की विरासत और साझेदारी के अनुभव को दर्शाते हैं — न कि यह दावा करते हैं कि प्रत्येक ऐतिहासिक प्रोजेक्ट सीधे दक्षिण अफ्रीकी (एसएडीएसी) इकाई के रूप में एआरएसएसए द्वारा शुरू किया गया था। यह ट्रैक रिकॉर्ड परिचालन क्षमता, क्षेत्र के ज्ञान और कॉर्पोरेट संबंधों को रेखांकित करता है जो एआरएसएसए आज दक्षिण अफ्रीकी (एसएडीएसी) ग्राहकों के लिए लाता है।",
    ru: "Представленные ниже исторические проекты отражают наследие и партнерский опыт ARS Group в ДРК — без утверждения о том, что каждый из них выполнялся непосредственно южноафриканской компанией ARSSA. Этот послужной список подтверждает масштаб операционных возможностей, отраслевую экспертизу и деловые связи, которые ARSSA предоставляет сегодня южноафриканским (SADAC) клиентам.",
    ja: "以下に掲載する実績は、ARS グループがコンゴ民主共和国で培ってきた歴史と提携実績を反映したものであり、すべてのプロジェクトが南アフリカ法人としての ARSSA によって直接遂行されたことを意味するものではありません。この確かな実績こそが、今日 ARSSA が南アフリカ（SADAC）のクライアントに提供する現場運用力、業界知見、強固な企業ネットワークの礎となっています。",
    ko: "아래 소개된 과거 프로젝트들은 콩고민주공화국에서 구축한 ARS 그룹의 헤리티지와 파트너십 역사를 반영한 것으로, 모든 프로젝트가 남아프리카공화국(SADAC) 법인인 ARSSA에 의해 직접 수행되었음을 주장하는 것은 아닙니다. 이러한 축적된 실적은 오늘날 ARSSA가 남아공(SADAC) 고객에게 제공하는 탁월한 운영 역량, 산업 전문성 및 기업 네트워크의 든든한 토대입니다.",
    it: "I progetti storici presentati di seguito riflettono l'eredità e l'esperienza di partnership del Gruppo ARS nella RDC, senza pretendere che ogni progetto storico sia stato intrapreso direttamente da ARSSA in quanto entità sudafricana (SADAC). Questo track record è alla base della capacità operativa, della conoscenza settoriale e delle relazioni aziendali che ARSSA offre oggi ai clienti sudafricani (SADAC).",
    nl: "De hieronder getoonde historische projecten weerspiegelen de ervaring en het partnerschapsnetwerk van de ARS Groep in de DRC — zonder te beweren dat elk project rechtstreeks is uitgevoerd door ARSSA als Zuid-Afrikaanse (SADAC) entiteit. Dit trackrecord vormt het fundament onder de operationele slagkracht, sectorkennis en zakelijke relaties die ARSSA vandaag aanbiedt aan Zuid-Afrikaanse (SADAC) opdrachtgevers.",
  },
  "A representative selection of complex civil, medical, financial, and industrial projects executed in the DRC.": {
    en: "A representative selection of complex civil, medical, financial, and industrial projects executed in the DRC.",
    fr: "Une sélection représentative de projets civils, médicaux, financiers et industriels complexes exécutés en RDC.",
    pt: "Uma selecção representativa de projectos civis, médicos, financeiros e industriais complexos executados na RDC.",
    sw: "Uteuzi mwakilishi wa miradi tata ya ujenzi, matibabu, fedha na viwanda iliyotekelezwa nchini DRC.",
    ln: "Ndambo ya misala ya minene ya botongi, ya monganga, ya mbongo mpe ya ba izine oyo esalemi na RDC.",
    af: "'n Verteenwoordigende keur van komplekse siviele, mediese, finansiële en industriële projekte wat in die DRK uitgevoer is.",
    zu: "Ukukhethwa okumele kwamaphrojekthi ayinkimbinkimbi okwakha, ezokwelapha, ezezimali, nezimboni enziwe e-DRC.",
    xh: "Ukhetho olumele iiprojekthi ezinzima zolwakhiwo, ezonyango, ezemali, nezoshishino ezenziwe e-DRC.",
    zh: "在刚果（金）境内成功交付的一系列具有代表性的重大民建工程、医疗基础设施、金融机构分支及工业级项目。",
    ar: "مجموعة مختارة وممثلة لمشاريع معقدة في المجالات المدنية والطبية والمالية والصناعية نُفذت بنجاح في جمهورية الكونغو الديمقراطية.",
    es: "Una selección representativa de proyectos civiles, médicos, financieros e industriales complejos ejecutados en la RDC.",
    de: "Eine repräsentative Auswahl anspruchsvoller Bau-, Medizin-, Finanz- und Industrieprojekte in der DR Kongo.",
    hi: "डीआरसी में निष्पादित जटिल नागरिक, चिकित्सा, वित्तीय और औद्योगिक परियोजनाओं का एक प्रतिनिधि चयन।",
    ru: "Репрезентативная подборка сложных строительных, медицинских, финансовых и промышленных проектов, реализованных в ДРК.",
    ja: "コンゴ民主共和国で遂行された、土木建築、医療施設、金融機関、産業インフラにおける代表的な大規模プロジェクト群。",
    ko: "콩고민주공화국에서 성공적으로 완수된 건설 토목, 의료 인프라, 금융 및 산업 분야의 대표적인 프로젝트들입니다.",
    it: "Una selezione rappresentativa di complessi progetti civili, medici, finanziari e industriali realizzati nella RDC.",
    nl: "Een representatieve selectie van complexe civiele, medische, financiële en industriële projecten die zijn gerealiseerd in de DRC.",
  },
  "What This Demonstrates": {
    en: "What This Demonstrates",
    fr: "Ce que Cela Démontre",
    pt: "O Que Isto Demonstra",
    sw: "Kile Hiki Kinachoonyesha",
    ln: "Nini Yango Ezali Kolakisa",
    af: "Wat Dit Demonstreer",
    zu: "Lokho Lokhu Okukubonisayo",
    xh: "Into Eboniswa Yile Nto",
    zh: "核心价值与实力佐证",
    ar: "ما يبرهنه هذا السجل",
    es: "Lo que Esto Demuestra",
    de: "Was dies belegt",
    hi: "यह क्या दर्शाता है",
    ru: "Что это доказывает",
    ja: "実績が証明するもの",
    ko: "이 실적이 입증하는 역량",
    it: "Cosa Dimostra Questo",
    nl: "Wat Dit Aantoont",
  },
  "This legacy demonstrates operational capacity, experience with complex and regulated projects, and long-standing trust with major corporate and government clients.": {
    en: "This legacy demonstrates operational capacity, experience with complex and regulated projects, and long-standing trust with major corporate and government clients.",
    fr: "Cet héritage démontre notre capacité opérationnelle, notre expérience des projets complexes et réglementés, ainsi qu'une confiance durable avec de grands clients d'entreprise et gouvernementaux.",
    pt: "Este legado demonstra capacidade operacional, experiência em projectos complexos e regulamentados e confiança duradoura com grandes clientes corporativos e governamentais.",
    sw: "Urithi huu unaonyesha uwezo wa kiutendaji, uzoefu na miradi tata na inayodhibitiwa, na uaminifu wa muda mrefu na wateja wakuu wa makampuni na serikali.",
    ln: "Misala oyo ezali kolakisa makoki ya solo ya mosala, mayele ya kosala misala ya mikakatano mpe ya kotosa mibeko, mpe motema molai oyo bakompani minene mpe leta bazali na yango epai na biso.",
    af: "Hierdie nalatenskap demonstreer operasionele kapasiteit, ervaring met komplekse en gereguleerde projekte, en jarelange vertroue by groot korporatiewe en regeringskliënte.",
    zu: "Leli fa libonisa amandla okusebenza, isipiliyoni ngamaphrojekthi ayinkimbinkimbi nalawulwayo, nokwethenjwa kwesikhathi eside namakhasimende amakhulu ezinkampani nahulumeni.",
    xh: "Eli lifa libonisa amandla okusebenza, amava ngeeprojekthi ezinzima nezilawulwayo, nokuthenjwa kwexesha elide nabathengi abakhulu benkampani nabakarhulumente.",
    zh: "这份历史底蕴充分彰显了我们在复杂高规格监管环境下的强大落地执行力、重大项目承办经验以及深受大型跨国企业与政府信赖的商誉基石。",
    ar: "يبرهن هذا الإرث على قدرتنا التشغيلية وخبرتنا الواسعة في المشاريع المعقدة والمنظمة، والثقة الراسخة طويلة الأمد مع كبرى الشركات والجهات الحكومية.",
    es: "Este legado demuestra capacidad operativa, experiencia en proyectos complejos y regulados, y una confianza duradera con importantes clientes corporativos y gubernamentales.",
    de: "Dieses Erbe beweist operative Leistungsfähigkeit, Erfahrung mit anspruchsvollen und regulierten Projekten sowie langjähriges Vertrauen bei großen Unternehmens- und Regierungskunden.",
    hi: "यह विरासत परिचालन क्षमता, जटिल और विनियमित परियोजनाओं के अनुभव और प्रमुख कॉर्पोरेट और सरकारी ग्राहकों के साथ लंबे समय से चले आ रहे विश्वास को प्रदर्शित करती है।",
    ru: "Этот опыт доказывает высокую операционную надежность, глубокие компетенции в сложных регулируемых отраслях и многолетнее доверие со стороны корпоративных и государственных заказчиков.",
    ja: "この実績は、高度な法規制を伴う複雑なプロジェクトを完遂する卓越した現場実行力、ならびに大手企業や政府機関から長年寄せられている確固たる信頼を如実に証明しています。",
    ko: "이러한 헤리티지는 대규모 복합 규제 프로젝트를 안정적으로 완수하는 독보적인 운영 역량과 유수의 대기업 및 정부 기관으로부터 받아온 오랜 신뢰를 증명합니다.",
    it: "Questa eredità dimostra capacità operativa, esperienza con progetti complessi e regolamentati e una fiducia duratura con importanti clienti aziendali e governativi.",
    nl: "Deze staat van dienst bewijst onze operationele capaciteit, ervaring met complexe en gereguleerde projecten en het langdurige vertrouwen van toonaangevende zakelijke en overheidsinstanties.",
  },
  "Ask us about the ARS Group's track record in your vertical — we are glad to discuss relevant project execution in detail.": {
    en: "Ask us about the ARS Group's track record in your vertical — we are glad to discuss relevant project execution in detail.",
    fr: "Interrogez-nous sur les réalisations du Groupe ARS dans votre secteur — nous serons ravis d'échanger en détail sur les projets correspondants.",
    pt: "Pergunte-nos sobre o historial do Grupo ARS no seu sector — teremos todo o gosto em discutir detalhadamente a execução de projectos relevantes.",
    sw: "Tuulize kuhusu rekodi ya Kikundi cha ARS katika sekta yako — tunafurahi kujadili utekelezaji wa miradi husika kwa kina.",
    ln: "Tuna biso mpo na misala oyo Groupe ARS esili kosala na mosala na yo — tokomona esengo ya kolobela makambo yango na bozindo.",
    af: "Vra ons oor die ARS Groep se baanrekord in u bedryf — ons gesels graag in detail oor relevante projekuitvoering.",
    zu: "Sibuze ngomlando we-ARS Group emkhakheni wakho — siyajabula ukuxoxa ngokwenziwa kwephrojekthi efanele ngokuningiliziwe.",
    xh: "Sibuze ngerekhodi yeQela le-ARS kwicandelo lakho — sinovuyo lokuxoxa ngokwenziwa kweprojekthi efanelekileyo ngokweenkcukacha.",
    zh: "欢迎垂询 ARS 集团在您所在行业的真实历史执行案例与履约成果 —— 我们十分乐意与您深入分享相关项目细节。",
    ar: "اسألنا عن سجل إنجازات مجموعة ARS في قطاع عملك — يسعدنا مناقشة تنفيذ المشاريع المماثلة بالتفصيل.",
    es: "Pregúntenos sobre el historial del Grupo ARS en su sector; con gusto analizaremos la ejecución de proyectos relevantes en detalle.",
    de: "Fragen Sie uns nach der Erfolgsbilanz der ARS-Gruppe in Ihrer Branche — wir erläutern Ihnen gerne relevante Projektdetails.",
    hi: "अपने क्षेत्र में एआरएस ग्रुप के ट्रैक रिकॉर्ड के बारे में हमसे पूछें — हमें प्रासंगिक परियोजना निष्पादन पर विस्तार से चर्चा करने में खुशी होगी।",
    ru: "Узнайте о реализованных проектах ARS Group в вашей отрасли — мы с удовольствием предоставим подробную информацию о выполненных задачах.",
    ja: "貴社業界における ARS グループの具体的な実績について、ぜひお気軽にお問い合わせください。関連プロジェクトの詳細を喜んでご説明いたします。",
    ko: "귀사 산업 분야에서의 ARS 그룹 실적에 대해 문의해 주세요. 관련 프로젝트의 실행 상세 내역을 기꺼이 공유해 드리겠습니다.",
    it: "Chiedici maggiori informazioni sullo storico del Gruppo ARS nel tuo settore: saremo lieti di discutere in dettaglio l'esecuzione dei progetti pertinenti.",
    nl: "Vraag ons naar de resultaten van de ARS Groep in uw sector — we gaan graag nader in op de details van relevante projecten.",
  },
  "Request a Discussion": {
    en: "Request a Discussion",
    fr: "Demander un Entretien",
    pt: "Solicitar uma Reunião",
    sw: "Omba Mazungumzo",
    ln: "Senga Masolo",
    af: "Vra 'n Gesprek aan",
    zu: "Cela Ingxoxo",
    xh: "Cela Ingxoxo",
    zh: "预约深度沟通",
    ar: "طلب مناقشة عمل",
    es: "Solicitar una Reunión",
    de: "Gespräch anfragen",
    hi: "चर्चा का अनुरोध करें",
    ru: "Запросить консультацию",
    ja: "個別相談を申し込む",
    ko: "전문 상담 신청",
    it: "Richiedi un Confronto",
    nl: "Vraag een Gesprek aan",
  },
  "Every corporate enquiry is reviewed directly by our management team. We respond with an honest evaluation of how ARSSA can de-risk and accelerate your goals.": {
    en: "Every corporate enquiry is reviewed directly by our management team. We respond with an honest evaluation of how ARSSA can de-risk and accelerate your goals.",
    fr: "Chaque demande d'entreprise est examinée directement par notre équipe de direction. Nous répondons par une évaluation honnête de la manière dont ARSSA peut réduire les risques et accélérer vos objectifs.",
    pt: "Cada consulta corporativa é analisada directamente pela nossa equipa de gestão. Respondemos com uma avaliação honesta de como a ARSSA pode reduzir riscos e acelerar os seus objectivos.",
    sw: "Kila swali la kampuni linakaguliwa moja kwa moja na timu yetu ya usimamizi. Tunajibu kwa tathmini ya kweli ya jinsi ARSSA inavyoweza kupunguza hatari na kuharakisha malengo yako.",
    ln: "Mituna nyonso ya bakompani etalelamaka mbala moko na bakambi ya kompani. Tokopesa eyano ya sembo na ndenge nini ARSSA ekoki kolongola likama mpe kosala ete kokoma na mikano na yo eza noki.",
    af: "Elke korporatiewe navraag word direk deur ons bestuurspan nagegaan. Ons reageer met 'n eerlike evaluering van hoe ARSSA risiko's kan verminder en u doelwitte kan versnel.",
    zu: "Yonke imibuzo yenkampani ibuyekezwa ngokuqondile yithimba lethu labaphathi. Siphendula ngokuhlola okuthembekile kokuthi i-ARSSA ingabunciphisa kanjani ubungozi futhi isheshise imigomo yakho.",
    xh: "Yonke imibuzo yenkampani iphononongwa ngokuthe ngqo liqela lethu labaphathi. Siphendula ngovavanyo olunyanisekileyo lwendlela i-ARSSA enokunciphisa ngayo umngcipheko nokukhawulezisa iinjongo zakho.",
    zh: "每一份企业合作咨询均由我们高管管理团队直接亲自审阅。我们将为您提供客观坦诚的可行性评估，阐明 ARSSA 如何为您的目标化解风险、保驾护航并加快进度。",
    ar: "تتم مراجعة كل استفسار للشركات مباشرة من قبل فريق الإدارة لدينا. نرد بتقييم صادق وموضوعي لكيفية قيام ARSSA بتقليل المخاطر وتسريع أهدافك.",
    es: "Cada consulta corporativa es revisada directamente por nuestro equipo directivo. Respondemos con una evaluación honesta de cómo ARSSA puede mitigar riesgos y acelerar sus objetivos.",
    de: "Jede Unternehmensanfrage wird direkt von unserer Geschäftsleitung geprüft. Wir antworten mit einer ehrlichen Einschätzung, wie ARSSA Risiken minimieren und Ihre Ziele beschleunigen kann.",
    hi: "प्रत्येक कॉर्पोरेट पूछताछ की समीक्षा सीधे हमारी प्रबंधन टीम द्वारा की जाती है। हम इस बात का ईमानदार मूल्यांकन करते हैं कि ARSSA आपके लक्ष्यों को कैसे जोखिम मुक्त और गति दे सकता है।",
    ru: "Каждый корпоративный запрос рассматривается непосредственно нашей руководящей командой. Мы даем честную оценку того, как ARSSA поможет снизить риски и ускорить достижение ваших целей.",
    ja: "すべての法人からのお問い合わせは、当社の経営陣が直接精査いたします。ARSSA がどのようにリスクを低減し、目標達成を加速できるか、率直かつ的確な評価をお答えします。",
    ko: "모든 기업 문의는 당사 경영진이 직접 검토합니다. ARSSA가 귀사의 비즈니스 위험을 어떻게 완화하고 목표를 신속하게 달성할 수 있는지 솔직하고 실질적인 평가를 제공합니다.",
    it: "Ogni richiesta aziendale viene esaminata direttamente dal nostro team di gestione. Rispondiamo con una valutazione onesta di come ARSSA può ridurre i rischi e accelerare i tuoi obiettivi.",
    nl: "Elke zakelijke aanvraag wordt rechtstreeks beoordeeld door ons managementteam. We reageren met een eerlijke evaluatie van hoe ARSSA risico's kan beperken en uw doelstellingen kan versnellen.",
  },
  "You can contact our team directly via telephone, WhatsApp or email before submitting a formal scope.": {
    en: "You can contact our team directly via telephone, WhatsApp or email before submitting a formal scope.",
    fr: "Vous pouvez contacter directement notre équipe par téléphone, WhatsApp ou e-mail avant de soumettre un projet formel.",
    pt: "Pode contactar a nossa equipa directamente por telefone, WhatsApp ou e-mail antes de submeter um pedido formal.",
    sw: "Unaweza kuwasiliana na timu yetu moja kwa moja kupitia simu, WhatsApp au barua pepe kabla ya kuwasilisha maelezo rasmi ya mradi.",
    ln: "Okoki kobenga ekipi na biso mbala moko na telefone, WhatsApp to email liboso ya kopesa mikanda ya solosolo ya mosala.",
    af: "U kan ons span direk kontak via telefoon, WhatsApp of e-pos voordat u 'n formele bestek indien.",
    zu: "Ungaxhumana nethimba lethu ngokuqondile ngocingo, i-WhatsApp noma i-imeyili ngaphambi kokuhambisa uhlaka olusemthethweni.",
    xh: "Ungaqhagamshelana neqela lethu ngokuthe ngqo ngefowuni, WhatsApp okanye i-imeyile ngaphambi kokuba ungenise isicwangciso esisemthethweni.",
    zh: "在提交正式业务范围之前，您亦可随时通过电话、WhatsApp 或电子邮件与我们的团队取得直接联系。",
    ar: "يمكنك الاتصال بفريقنا مباشرة عبر الهاتف أو WhatsApp أو البريد الإلكتروني قبل تقديم نطاق عمل رسمي.",
    es: "Puede ponerse en contacto con nuestro equipo directamente por teléfono, WhatsApp o correo electrónico antes de enviar una solicitud formal.",
    de: "Sie können unser Team vor der Einreichung eines formellen Projektumfangs auch direkt per Telefon, WhatsApp oder E-Mail kontaktieren.",
    hi: "आप औपचारिक दायरा जमा करने से पहले टेलीफोन, व्हाट्सएप या ईमेल के माध्यम से सीधे हमारी टीम से संपर्क कर सकते हैं।",
    ru: "Вы можете связаться с нами напрямую по телефону, в WhatsApp или по электронной почте еще до отправки официального технического задания.",
    ja: "正式な仕様書・要件書を提出される前に、お電話、WhatsApp、または電子メールで当社チームまで直接ご相談いただくことも可能です。",
    ko: "공식적인 사업 제안서를 제출하기 전이라도 전화, WhatsApp 또는 이메일을 통해 당사 팀에 언제든 직접 문의하실 수 있습니다.",
    it: "Puoi contattare direttamente il nostro team tramite telefono, WhatsApp o e-mail prima di inviare un ambito formale.",
    nl: "U kunt rechtstreeks contact opnemen met ons team via telefoon, WhatsApp of e-mail voordat u een formele aanvraag indient.",
  },
  "Share your expansion objectives, industry sector, and estimated project scope.": {
    en: "Share your expansion objectives, industry sector, and estimated project scope.",
    fr: "Partagez vos objectifs d'expansion, votre secteur d'activité et la portée estimée de votre projet.",
    pt: "Partilhe os seus objectivos de expansão, sector de actividade e âmbito estimado do projecto.",
    sw: "Shiriki malengo yako ya upanuzi, sekta ya viwanda, na upeo unaokadiriwa wa mradi.",
    ln: "Yebisa biso mikano na yo ya bokoli, eteni ya mombo na yo mpe motuya ya mosala oyo okani kosala.",
    af: "Deel u uitbreidingsdoelwitte, bedryfsektor en beraamde projekomvang.",
    zu: "Yabelana ngezinhloso zakho zokunweba, umkhakha wemboni, nobukhulu bephrojekthi obulinganiselwe.",
    xh: "Yabelana ngeenjongo zakho zokwandisa, icandelo lezoshishino, nobukhulu beprojekthi obuqikelelweyo.",
    zh: "告知我们您的市场拓展目标、所属行业领域以及初步拟定的项目规模。",
    ar: "شارك أهدافك التوسعية، وقطاع عملك، ونطاق المشروع التقديري.",
    es: "Comparta sus objetivos de expansión, sector industrial y alcance estimado del proyecto.",
    de: "Teilen Sie uns Ihre Expansionsziele, Ihre Branche und den geschätzten Projektumfang mit.",
    hi: "अपने विस्तार के उद्देश्यों, उद्योग क्षेत्र और अनुमानित परियोजना के दायरे को साझा करें।",
    ru: "Опишите цели расширения, отраслевой сектор и предполагаемый масштаб проекта.",
    ja: "進出目標、対象業界、および想定されるプロジェクト規模をお知らせください。",
    ko: "사업 확장 목표, 해당 산업 부문 및 대략적인 프로젝트 범위를 알려주세요.",
    it: "Condividi i tuoi obiettivi di espansione, il settore industriale e l'ambito stimato del progetto.",
    nl: "Deel uw uitbreidingsdoelen, sector en geschatte projectomvang.",
  },
  "Our team reviews your regulatory and operational requirements against our capabilities.": {
    en: "Our team reviews your regulatory and operational requirements against our capabilities.",
    fr: "Notre équipe examine vos exigences réglementaires et opérationnelles au regard de nos capacités.",
    pt: "A nossa equipa analisa os seus requisitos regulamentares e operacionais em relação às nossas capacidades.",
    sw: "Timu yetu inakagua mahitaji yako ya kikanuni na kiutendaji kulinganisha na uwezo wetu.",
    ln: "Ekipi na biso ekotola masenga na yo ya mibeko mpe ya mosala kotalela makoki na biso.",
    af: "Ons span hersien u regulatoriese en operasionele vereistes teen ons vermoëns.",
    zu: "Ithimba lethu libuyekeza izidingo zakho zokulawula nezokusebenza liqhathanise namakhono ethu.",
    xh: "Iqela lethu liphonononga iimfuno zakho zolawulo nezokusebenza xa lithelekiswa nezakhono zethu.",
    zh: "我们的专家团队将严格对照自身落地能力，详尽评估您的各项法规准入与实际运营诉求。",
    ar: "يقوم فريقنا بمراجعة متطلباتك التنظيمية والتشغيلية وفقاً لقدراتنا وخبراتنا الميدانية.",
    es: "Nuestro equipo evalúa sus requisitos regulatorios y operativos en función de nuestras capacidades.",
    de: "Unser Team gleicht Ihre regulatorischen und operativen Anforderungen mit unseren Kapazitäten ab.",
    hi: "हमारी टीम हमारी क्षमताओं के विरुद्ध आपकी विनियामक और परिचालन आवश्यकताओं की समीक्षा करती है।",
    ru: "Наша команда сопоставит ваши регуляторные и операционные требования с нашими возможностями.",
    ja: "当社のチームが、貴社の法規制および運用上の要件を当社の対応能力に照らし合わせて精査します。",
    ko: "당사 팀이 귀사의 규제 및 운영 요건을 분석하여 당사의 역량과 대조 검토합니다.",
    it: "Il nostro team esamina i tuoi requisiti normativi e operativi rispetto alle nostre capacità.",
    nl: "Ons team toetst uw regelgevende en operationele behoeften aan onze mogelijkheden.",
  },
  "We respond with a practical recommendation, clear deliverables, and next steps — with zero obligation.": {
    en: "We respond with a practical recommendation, clear deliverables, and next steps — with zero obligation.",
    fr: "Nous répondons par une recommandation pratique, des livrables clairs et les étapes suivantes — sans aucun engagement.",
    pt: "Respondemos com uma recomendação prática, entregáveis claros e os próximos passos — sem qualquer compromisso.",
    sw: "Tunajibu kwa pendekezo la vitendo, matokeo wazi, na hatua zifuatazo — bila wajibu wowote.",
    ln: "Tokozongisela yo toli ya solo ya kosala, makambo oyo ekosalema polele mpe makambo oyo ekolanda — kozanga kopusama na makasi.",
    af: "Ons reageer met 'n praktiese aanbeveling, duidelike lewerbares en volgende stappe — met geen verpligting nie.",
    zu: "Siphendula ngesincomo esisebenzayo, okuzolethwa okucacile, nezinyathelo ezilandelayo — ngaphandle kwesibopho.",
    xh: "Siphendula ngesindululo esisebenzayo, izinto ezicacileyo ezinikezelwayo, namanyathelo alandelayo — ngaphandle kwembopheleleko.",
    zh: "我们将向您提供切实可行的落地方案建议、明晰的交付成果清单与后续推进步骤 —— 全程零捆绑承诺。",
    ar: "نرد بتوصية عملية، ونتائج واضحة، والخطوات التالية — دون أي التزام مسبق.",
    es: "Respondemos con una recomendación práctica, entregables claros y los siguientes pasos, sin compromiso alguno.",
    de: "Wir antworten mit einer praxisnahen Empfehlung, klaren Ergebnissen und den nächsten Schritten — völlig unverbindlich.",
    hi: "हम एक व्यावहारिक सिफारिश, स्पष्ट डिलिवरेबल्स और अगले कदमों के साथ जवाब देते हैं — शून्य दायित्व के साथ।",
    ru: "Мы предоставим практические рекомендации, перечень результатов и план дальнейших действий — без каких-либо обязательств с вашей стороны.",
    ja: "実践的なご提案、明確な成果物、および次のステップをご提示いたします（契約の義務は一切ございません）。",
    ko: "실질적인 권장사항, 명확한 산출물 및 향후 단계가 포함된 제안을 회신해 드립니다 — 어떠한 의무 사항도 없습니다.",
    it: "Rispondiamo con una raccomandazione pratica, risultati chiari e i passaggi successivi, senza alcun vincolo.",
    nl: "Wij reageren met een praktisch advies, heldere deliverables en vervolgstappen — geheel vrijblijvend.",
  },
};

let content = fs.readFileSync(phrasesFilePath, "utf8");
const match = content.match(/export const UNIVERSAL_PHRASES: Record<string, Partial<Record<Language, string>>> = (\{[\s\S]*\});\n$/);
if (!match) {
  console.error("Could not find UNIVERSAL_PHRASES");
  process.exit(1);
}
const existing = eval("(" + match[1] + ")");
const merged = { ...existing, ...CAT1_PHRASES };

const newPhrasesCode =
  `import type { Language } from "./languages";\n\n` +
  `export const UNIVERSAL_PHRASES: Record<string, Partial<Record<Language, string>>> = ` +
  JSON.stringify(merged, null, 2) +
  `;\n`;

fs.writeFileSync(phrasesFilePath, newPhrasesCode, "utf8");
console.log("Successfully updated universalPhrases.ts with Category 1, total keys:", Object.keys(merged).length);
