const fs = require("fs");
const path = require("path");

const phrasesFilePath = path.join(__dirname, "../src/translations/universalPhrases.ts");

const CAT3_PHRASES = {
  // Form options and placeholders
  "Select a service…": {
    en: "Select a service…",
    fr: "Sélectionnez un service…",
    pt: "Seleccione um serviço…",
    sw: "Chagua huduma…",
    ln: "Pona mosala…",
    af: "Kies 'n diens…",
    zu: "Khetha isevisi…",
    xh: "Khetha inkonzo…",
    zh: "请选择所需服务类别…",
    ar: "اختر الخدمة المطلوبة…",
    es: "Seleccione un servicio…",
    de: "Wählen Sie eine Dienstleistung…",
    hi: "एक सेवा चुनें…",
    ru: "Выберите услугу…",
    ja: "サービスを選択してください…",
    ko: "서비스를 선택해 주세요…",
    it: "Seleziona un servizio…",
    nl: "Selecteer een dienst…",
  },
  "Industry": {
    en: "Industry",
    fr: "Secteur d'Activité",
    pt: "Sector de Actividade",
    sw: "Sekta ya Viwanda",
    ln: "Eteni ya Mosala",
    af: "Bedryf",
    zu: "Imboni",
    xh: "Umzi-mveliso",
    zh: "所属行业",
    ar: "القطاع الصناعي",
    es: "Sector Industrial",
    de: "Branche",
    hi: "उद्योग",
    ru: "Отрасль промышленности",
    ja: "業種・業界",
    ko: "산업 분야",
    it: "Settore",
    nl: "Sector",
  },
  "Select an industry…": {
    en: "Select an industry…",
    fr: "Sélectionnez un secteur…",
    pt: "Seleccione um sector…",
    sw: "Chagua sekta ya viwanda…",
    ln: "Pona eteni ya mosala…",
    af: "Kies 'n bedryf…",
    zu: "Khetha imboni…",
    xh: "Khetha umzi-mveliso…",
    zh: "请选择所属行业…",
    ar: "اختر القطاع…",
    es: "Seleccione un sector…",
    de: "Wählen Sie eine Branche…",
    hi: "एक उद्योग चुनें…",
    ru: "Выберите отрасль…",
    ja: "業種を選択してください…",
    ko: "산업 분야를 선택해 주세요…",
    it: "Seleziona un settore…",
    nl: "Selecteer een sector…",
  },
  "How did you hear about us?": {
    en: "How did you hear about us?",
    fr: "Comment avez-vous entendu parler de nous ?",
    pt: "Como soube de nós?",
    sw: "Ulisikiaje kutuhusu?",
    ln: "Oyokaki sango na biso ndenge nini?",
    af: "Hoe het u van ons gehoor?",
    zu: "Uzwe kanjani ngathi?",
    xh: "Uve njani ngathi?",
    zh: "您是如何得知我们的？",
    ar: "كيف سمعت عنا؟",
    es: "¿Cómo se enteró de nosotros?",
    de: "Wie haben Sie von uns erfahren?",
    hi: "आपने हमारे बारे में कैसे सुना?",
    ru: "Как вы узнали о нас?",
    ja: "当社をどこでお知りになりましたか？",
    ko: "당사를 어떻게 알게 되셨나요?",
    it: "Come hai saputo di noi?",
    nl: "Hoe heeft u over ons gehoord?",
  },
  "Select an option…": {
    en: "Select an option…",
    fr: "Sélectionnez une option…",
    pt: "Seleccione uma opção…",
    sw: "Chagua chaguo…",
    ln: "Pona ndenge moko…",
    af: "Kies 'n opsie…",
    zu: "Khetha inketho…",
    xh: "Khetha ukhetho…",
    zh: "请选择一个选项…",
    ar: "اختر خياراً…",
    es: "Seleccione una opción…",
    de: "Wählen Sie eine Option…",
    hi: "एक विकल्प चुनें…",
    ru: "Выберите вариант…",
    ja: "オプションを選択してください…",
    ko: "옵션을 선택해 주세요…",
    it: "Seleziona un'opzione…",
    nl: "Selecteer een optie…",
  },
  "Estimated Project Scope": {
    en: "Estimated Project Scope",
    fr: "Portée Estimée du Projet",
    pt: "Âmbito Estimado do Projecto",
    sw: "Upeo Unaokadiriwa wa Mradi",
    ln: "Motuya mpe Monene ya Mosala",
    af: "Beraamde Projekomvang",
    zu: "Ubukhulu Bephrojekthi Obulinganiselwe",
    xh: "Ubukhulu Beprojekthi Obuqikelelweyo",
    zh: "拟定项目规模与预期预算",
    ar: "نطاق المشروع التقديري",
    es: "Alcance Estimado del Proyecto",
    de: "Geschätzter Projektumfang",
    hi: "अनुमानित परियोजना का दायरा",
    ru: "Ориентировочный масштаб проекта",
    ja: "想定プロジェクト規模",
    ko: "예상 프로젝트 범위",
    it: "Ambito Stimato del Progetto",
    nl: "Geschatte Projectomvang",
  },
  "Tell us about your project or enquiry...": {
    en: "Tell us about your project or enquiry...",
    fr: "Parlez-nous de votre projet ou de votre demande...",
    pt: "Conte-nos sobre o seu projecto ou consulta...",
    sw: "Tueleze kuhusu mradi au swali lako...",
    ln: "Yebisa biso mpo na mosala to motuna na yo...",
    af: "Vertel ons van u projek of navraag...",
    zu: "Sitshele ngephrojekthi yakho noma umbuzo...",
    xh: "Sixelele ngeprojekthi yakho okanye ngombuzo wakho...",
    zh: "请向我们详述您的项目需求或业务咨询…",
    ar: "أخبرنا عن مشروعك أو استفسارك...",
    es: "Cuéntenos sobre su proyecto o consulta...",
    de: "Erzählen Sie uns von Ihrem Projekt oder Anliegen...",
    hi: "हमें अपनी परियोजना या पूछताछ के बारे में बताएं...",
    ru: "Расскажите подробнее о вашем проекте или запросе...",
    ja: "プロジェクトやご相談内容の詳細についてお聞かせください…",
    ko: "프로젝트 또는 문의 사항에 대해 자세히 알려주세요...",
    it: "Raccontaci del tuo progetto o della tua richiesta...",
    nl: "Vertel ons over uw project of aanvraag...",
  },
  "Tell us what you need and how ARSSA can support your objectives…": {
    en: "Tell us what you need and how ARSSA can support your objectives…",
    fr: "Dites-nous ce dont vous avez besoin et comment ARSSA peut soutenir vos objectifs…",
    pt: "Diga-nos do que necessita e como a ARSSA pode apoiar os seus objectivos…",
    sw: "Tueleze unachohitaji na jinsi ARSSA inavyoweza kusaidia malengo yako…",
    ln: "Yebisa biso nini olingi mpe ndenge nini ARSSA ekoki kosalisa mikano na yo…",
    af: "Vertel ons wat u benodig en hoe ARSSA u doelwitte kan ondersteun…",
    zu: "Sitshele ukuthi yini oyidingayo nokuthi i-ARSSA ingayisekela kanjani imigomo yakho…",
    xh: "Sixelele into oyifunayo nendlela i-ARSSA enokuzixhasa ngayo iinjongo zakho…",
    zh: "请说明您的具体诉求以及您希望 ARSSA 如何为您的商业目标提供助力…",
    ar: "أخبرنا بما تحتاجه وكيف يمكن لـ ARSSA دعم أهدافك…",
    es: "Cuéntenos qué necesita y cómo ARSSA puede respaldar sus objetivos…",
    de: "Sagen Sie uns, was Sie benötigen und wie ARSSA Ihre Ziele unterstützen kann…",
    hi: "हमें बताएं कि आपको क्या चाहिए और ARSSA आपके उद्देश्यों का कैसे समर्थन कर सकता है…",
    ru: "Опишите ваши потребности и то, как ARSSA может способствовать вашим целям…",
    ja: "貴社が必要とされているサポート内容、および ARSSA がどのように目標達成に貢献できるかお聞かせください…",
    ko: "필요하신 사항과 ARSSA가 귀사의 목표를 어떻게 지원할 수 있는지 알려주세요…",
    it: "Dicci di cosa hai bisogno e come ARSSA può supportare i tuoi obiettivi…",
    nl: "Vertel ons wat u nodig heeft en hoe ARSSA uw doelstellingen kan ondersteunen…",
  },
  "I agree to the processing of my information in accordance with the": {
    en: "I agree to the processing of my information in accordance with the",
    fr: "J'accepte le traitement de mes informations conformément à la",
    pt: "Concordo com o tratamento das minhas informações de acordo com a",
    sw: "Ninakubali kuchakatwa kwa taarifa zangu kwa mujibu wa",
    ln: "Nandimi ete basalela basango na ngai na kolanda",
    af: "Ek stem in tot die verwerking van my inligting ooreenkomstig die",
    zu: "Ngiyavuma ukucutshungulwa kwemininingwane yami ngokuhambisana ne",
    xh: "Ndiyavumelana nokusetyenziswa kweenkcukacha zam ngokuhambelana ne",
    zh: "我确认并同意按照相关规定处理我的个人信息：",
    ar: "أوافق على معالجة معلوماتي وفقاً لـ",
    es: "Acepto el tratamiento de mi información de conformidad con la",
    de: "Ich stimme der Verarbeitung meiner Daten gemäß der",
    hi: "मैं इसके अनुसार अपनी जानकारी के प्रसंस्करण के लिए सहमत हूँ:",
    ru: "Я согласен на обработку моих данных в соответствии с",
    ja: "以下の規程に従って個人情報が処理されることに同意します：",
    ko: "다음에 따른 본인의 개인정보 처리에 동의합니다:",
    it: "Accetto il trattamento dei miei dati in conformità con la",
    nl: "Ik ga akkoord met de verwerking van mijn gegevens in overeenstemming met het",
  },
  "Submit Enquiry": {
    en: "Submit Enquiry",
    fr: "Envoyer la Demande",
    pt: "Submeter Consulta",
    sw: "Wasilisha Swali",
    ln: "Tinda Motuna",
    af: "Dien Navraag In",
    zu: "Thumela Umbuzo",
    xh: "Genisa Umbuzo",
    zh: "提交合作咨询",
    ar: "إرسال الاستفسار",
    es: "Enviar Consulta",
    de: "Anfrage absenden",
    hi: "पूछताछ जमा करें",
    ru: "Отправить запрос",
    ja: "お問い合わせを送信する",
    ko: "문의 제출하기",
    it: "Invia Richiesta",
    nl: "Aanvraag Verzenden",
  },

  // Legal definitions and terms
  "\"Website\"": {
    en: "\"Website\"",
    fr: "\"Site Web\"",
    pt: "\"Site\"",
    sw: "\"Tovuti\"",
    ln: "\"Site\"",
    af: "\"Webwerf\"",
    zu: "\"Iwebhusayithi\"",
    xh: "\"Iwebhusayithi\"",
    zh: "“本网站”",
    ar: "\"الموقع الإلكتروني\"",
    es: "\"Sitio Web\"",
    de: "„Website“",
    hi: "\"वेबसाइट\"",
    ru: "«Сайт»",
    ja: "「ウェブサイト」",
    ko: "\"웹사이트\"",
    it: "\"Sito Web\"",
    nl: "\"Website\"",
  },
  "\"Services\"": {
    en: "\"Services\"",
    fr: "\"Services\"",
    pt: "\"Serviços\"",
    sw: "\"Huduma\"",
    ln: "\"Misala\"",
    af: "\"Dienste\"",
    zu: "\"Izinsizakalo\"",
    xh: "\"Iinkonzo\"",
    zh: "“服务”",
    ar: "\"الخدمات\"",
    es: "\"Servicios\"",
    de: "„Dienstleistungen“",
    hi: "\"सेवाएं\"",
    ru: "«Услуги»",
    ja: "「サービス」",
    ko: "\"서비스\"",
    it: "\"Servizi\"",
    nl: "\"Diensten\"",
  },
  "\"Client\"": {
    en: "\"Client\"",
    fr: "\"Client\"",
    pt: "\"Cliente\"",
    sw: "\"Mteja\"",
    ln: "\"Kiliya\"",
    af: "\"Kliënt\"",
    zu: "\"Iklayenti\"",
    xh: "\"Umthengi\"",
    zh: "“客户”",
    ar: "\"العميل\"",
    es: "\"Cliente\"",
    de: "„Kunde“",
    hi: "\"ग्राहक\"",
    ru: "«Клиент»",
    ja: "「クライアント」",
    ko: "\"고객사\"",
    it: "\"Cliente\"",
    nl: "\"Klant\"",
  },
  "\"Content\"": {
    en: "\"Content\"",
    fr: "\"Contenu\"",
    pt: "\"Conteúdo\"",
    sw: "\"Maudhui\"",
    ln: "\"Makambo ya Kati\"",
    af: "\"Inhoud\"",
    zu: "\"Okuqukethwe\"",
    xh: "\"Okuqulethweyo\"",
    zh: "“内容”",
    ar: "\"المحتوى\"",
    es: "\"Contenido\"",
    de: "„Inhalte“",
    hi: "\"सामग्री\"",
    ru: "«Контент»",
    ja: "「コンテンツ」",
    ko: "\"콘텐츠\"",
    it: "\"Contenuto\"",
    nl: "\"Inhoud\"",
  },
  "consent": {
    en: "consent",
    fr: "consentement",
    pt: "consentimento",
    sw: "idhini",
    ln: "ndingisa",
    af: "toestemming",
    zu: "imvume",
    xh: "imvume",
    zh: "知情同意",
    ar: "الموافقة",
    es: "consentimiento",
    de: "Einwilligung",
    hi: "सहमति",
    ru: "согласие",
    ja: "同意",
    ko: "동의",
    it: "consenso",
    nl: "toestemming",
  },
  "performance of a contract": {
    en: "performance of a contract",
    fr: "exécution d'un contrat",
    pt: "execução de um contrato",
    sw: "utekelezaji wa mkataba",
    ln: "bosali mikanda ya boyokani",
    af: "uitvoering van 'n kontrak",
    zu: "ukwenziwa kwenkontileka",
    xh: "ukwenziwa kwekhontrakthi",
    zh: "履行合同所需",
    ar: "تنفيذ العقد",
    es: "ejecución de un contrato",
    de: "Vertragserfüllung",
    hi: "अनुबंध का निष्पादन",
    ru: "исполнение договора",
    ja: "契約の履行",
    ko: "계약의 이행",
    it: "esecuzione di un contratto",
    nl: "uitvoering van een overeenkomst",
  },
  "legitimate interests": {
    en: "legitimate interests",
    fr: "intérêts légitimes",
    pt: "interesses legítimos",
    sw: "maslahi halali",
    ln: "matomba ya solo",
    af: "regmatige belange",
    zu: "izintshisekelo ezisemthethweni",
    xh: "iimfuno ezisemthethweni",
    zh: "合法正当权益",
    ar: "المصالح المشروعة",
    es: "intereses legítimos",
    de: "berechtigte Interessen",
    hi: "वैध हित",
    ru: "законные интересы",
    ja: "正当な利益",
    ko: "정당한 이익",
    it: "legittimi interessi",
    nl: "gerechtvaardigde belangen",
  },
  "Legal obligation": {
    en: "Legal obligation",
    fr: "Obligation légale",
    pt: "Obrigação legal",
    sw: "Wajibu wa kisheria",
    ln: "Mokumba ya mibeko",
    af: "Regsverpligting",
    zu: "Isibopho somthetho",
    xh: "Isibophelelo somthetho",
    zh: "法定义务",
    ar: "التزام قانوني",
    es: "Obligación legal",
    de: "Gesetzliche Verpflichtung",
    hi: "कानूनी दायित्व",
    ru: "Юридическое обязательство",
    ja: "法的義務",
    ko: "법적 의무",
    it: "Obbligo legale",
    nl: "Wettelijke verplichting",
  },
  "Access": {
    en: "Access",
    fr: "Accès",
    pt: "Acesso",
    sw: "Upatikanaji",
    ln: "Kozwa Nzela",
    af: "Toegang",
    zu: "Ukufinyelela",
    xh: "Ukufikelela",
    zh: "查阅权",
    ar: "حق الوصول",
    es: "Acceso",
    de: "Auskunftsrecht",
    hi: "पहुंच",
    ru: "Право на доступ",
    ja: "アクセス権",
    ko: "열람권",
    it: "Accesso",
    nl: "Inzage",
  },
  "Correction": {
    en: "Correction",
    fr: "Rectification",
    pt: "Rectificação",
    sw: "Marekebisho",
    ln: "Kobongisa",
    af: "Korreksie",
    zu: "Ukulungisa",
    xh: "Ukulungisa",
    zh: "更正权",
    ar: "حق التصحيح",
    es: "Rectificación",
    de: "Berichtigung",
    hi: "सुधार",
    ru: "Право на исправление",
    ja: "訂正権",
    ko: "정정권",
    it: "Rettifica",
    nl: "Rectificatie",
  },
  "Deletion": {
    en: "Deletion",
    fr: "Suppression",
    pt: "Eliminação",
    sw: "Kufuta",
    ln: "Kolimwisa",
    af: "Skrapping",
    zu: "Ukususa",
    xh: "Ukucima",
    zh: "删除权",
    ar: "حق الحذف",
    es: "Supresión",
    de: "Löschung",
    hi: "हटाना",
    ru: "Право на удаление",
    ja: "削除権",
    ko: "삭제권",
    it: "Cancellazione",
    nl: "Verwijdering",
  },
  "Objection": {
    en: "Objection",
    fr: "Opposition",
    pt: "Objecção",
    sw: "Kupinga",
    ln: "Kotelemela",
    af: "Beswaar",
    zu: "Ukuphikisa",
    xh: "Ukuchasa",
    zh: "异议权",
    ar: "حق الاعتراض",
    es: "Oposición",
    de: "Widerspruch",
    hi: "आपत्ति",
    ru: "Право на возражение",
    ja: "異議申立権",
    ko: "이의제기권",
    it: "Opposizione",
    nl: "Bezwaar",
  },
  "Withdraw consent": {
    en: "Withdraw consent",
    fr: "Retirer son consentement",
    pt: "Retirar o consentimento",
    sw: "Kuondoa idhini",
    ln: "Kolongola ndingisa",
    af: "Toestemming terugtrek",
    zu: "Ukuhoxisa imvume",
    xh: "Ukuhoxisa imvume",
    zh: "撤回同意权",
    ar: "سحب الموافقة",
    es: "Retirar el consentimiento",
    de: "Einwilligung widerrufen",
    hi: "सहमति वापस लेना",
    ru: "Отозвать согласие",
    ja: "同意の撤回",
    ko: "동의 철회권",
    it: "Revocare il consenso",
    nl: "Toestemming intrekken",
  },
  "Preference cookies": {
    en: "Preference cookies",
    fr: "Cookies de préférences",
    pt: "Cookies de preferências",
    sw: "Vidakuzi vya mapendeleo",
    ln: "Ba cookies ya bolingi",
    af: "Voorkeurkoekies",
    zu: "Amakuki wokukhetha",
    xh: "Ii-cookies zokhetho",
    zh: "偏好设置 Cookie",
    ar: "ملفات تعريف الارتباط الخاصة بالتفضيلات",
    es: "Cookies de preferencias",
    de: "Präferenz-Cookies",
    hi: "प्राथमिकता कुकीज़",
    ru: "Файлы cookie настроек",
    ja: "設定保持用クッキー",
    ko: "기능/설정 쿠키",
    it: "Cookie di preferenza",
    nl: "Voorkeurscookies",
  },
  "Third-party cookies": {
    en: "Third-party cookies",
    fr: "Cookies tiers",
    pt: "Cookies de terceiros",
    sw: "Vidakuzi vya washirika wa nje",
    ln: "Ba cookies ya bato mosusu",
    af: "Derdeparty-koekies",
    zu: "Amakuki abantu bangaphandle",
    xh: "Ii-cookies zangaphandle",
    zh: "第三方 Cookie",
    ar: "ملفات تعريف ارتباط تابعة لجهات خارجية",
    es: "Cookies de terceros",
    de: "Drittanbieter-Cookies",
    hi: "तृतीय-पक्ष कुकीज़",
    ru: "Файлы cookie третьих сторон",
    ja: "サードパーティクッキー",
    ko: "제3자 쿠키",
    it: "Cookie di terze parti",
    nl: "Cookies van derden",
  },
  "When you submit an enquiry or contact us, we may collect:": {
    en: "When you submit an enquiry or contact us, we may collect:",
    fr: "Lorsque vous soumettez une demande ou nous contactez, nous pouvons collecter :",
    pt: "Ao enviar uma consulta ou contactar-nos, poderemos recolher:",
    sw: "Unapowasilisha swali au kuwasiliana nasi, tunaweza kukusanya:",
    ln: "Tango otindi motuna to obengi biso, tokoki kozwa:",
    af: "Wanneer u 'n navraag indien of ons kontak, kan ons versamel:",
    zu: "Uma uhambisa umbuzo noma uxhumana nathi, singase siqoqe:",
    xh: "Xa ungenisa umbuzo okanye uqhagamshelana nathi, sinokuqokelela:",
    zh: "当您提交业务咨询或与我们联系时，我们可能会收集以下信息：",
    ar: "عند إرسال استفسار أو الاتصال بنا، قد نجمع:",
    es: "Cuando envía una consulta o se comunica con nosotros, podemos recopilar:",
    de: "Wenn Sie eine Anfrage einreichen oder uns kontaktieren, erfassen wir möglicherweise:",
    hi: "जब आप कोई पूछताछ सबमिट करते हैं या हमसे संपर्क करते हैं, तो हम एकत्र कर सकते हैं:",
    ru: "При отправке запроса или обращении к нам мы можем собирать:",
    ja: "お問い合わせやご連絡をいただいた際、当社は以下の情報を収集する場合があります：",
    ko: "문의를 제출하거나 당사에 연락하실 때 다음 정보를 수집할 수 있습니다:",
    it: "Quando invii una richiesta o ci contatti, potremmo raccogliere:",
    nl: "Wanneer u een aanvraag indient of contact met ons opneemt, kunnen we het volgende verzamelen:",
  },
  "We use the information we collect to:": {
    en: "We use the information we collect to:",
    fr: "Nous utilisons les informations collectées pour :",
    pt: "Utilizamos as informações recolhidas para:",
    sw: "Tunatumia taarifa tunazokusanya kwa ajili ya:",
    ln: "Tosalelaka basango oyo tozwi mpo na:",
    af: "Ons gebruik die inligting wat ons versamel om:",
    zu: "Sisebenzisa imininingwane esiyiqoqayo ukuze:",
    xh: "Sisebenzisa iinkcukacha esiziqokelelayo ukuze:",
    zh: "我们将所收集的信息严格用于以下合法目的：",
    ar: "نستخدم المعلومات التي نجمعها من أجل:",
    es: "Usamos la información que recopilamos para:",
    de: "Wir verwenden die erfassten Informationen, um:",
    hi: "हम अपने द्वारा एकत्र की गई जानकारी का उपयोग इसके लिए करते हैं:",
    ru: "Мы используем собранную информацию для следующих целей:",
    ja: "収集した情報は以下の目的で使用いたします：",
    ko: "수집된 정보는 다음 목적을 위해 사용됩니다:",
    it: "Utilizziamo le informazioni raccolte per:",
    nl: "Wij gebruiken de verzamelde gegevens om:",
  },
  "Under POPIA, you have the right to:": {
    en: "Under POPIA, you have the right to:",
    fr: "En vertu de la loi POPIA, vous avez le droit de :",
    pt: "Ao abrigo da POPIA, tem o direito de:",
    sw: "Chini ya POPIA, una haki ya:",
    ln: "Na nse ya mibeko POPIA, ozali na lotomo ya:",
    af: "Kragtens POPIA het u die reg om:",
    zu: "Ngaphansi kwe-POPIA, unelungelo loku:",
    xh: "Ngaphantsi kwe-POPIA, unelungelo loku:",
    zh: "根据《个人信息保护法》(POPIA)，您依法享有以下法定权利：",
    ar: "بموجب قانون حماية المعلومات الشخصية (POPIA)، يحق لك:",
    es: "Bajo POPIA, usted tiene derecho a:",
    de: "Gemäß POPIA haben Sie das Recht auf:",
    hi: "POPIA के तहत, आपको इसका अधिकार है:",
    ru: "В соответствии с законом POPIA вы имеете право:",
    ja: "POPIA（個人情報保護法）に基づき、お客様には以下の権利が認められています：",
    ko: "POPIA(개인정보보호법)에 따라 귀하는 다음 권리를 가집니다:",
    it: "Ai sensi del POPIA, hai il diritto di:",
    nl: "Onder POPIA heeft u het recht om:",
  },
};

let content = fs.readFileSync(phrasesFilePath, "utf8");
const match = content.match(/export const UNIVERSAL_PHRASES: Record<string, Partial<Record<Language, string>>> = (\{[\s\S]*\});\n$/);
if (!match) {
  console.error("Could not find UNIVERSAL_PHRASES");
  process.exit(1);
}
const existing = eval("(" + match[1] + ")");
const merged = { ...existing, ...CAT3_PHRASES };

const newPhrasesCode =
  `import type { Language } from "./languages";\n\n` +
  `export const UNIVERSAL_PHRASES: Record<string, Partial<Record<Language, string>>> = ` +
  JSON.stringify(merged, null, 2) +
  `;\n`;

fs.writeFileSync(phrasesFilePath, newPhrasesCode, "utf8");
console.log("Successfully updated universalPhrases.ts with Category 3, total keys:", Object.keys(merged).length);
