const fs = require("fs");
const path = require("path");

const phrasesFilePath = path.join(__dirname, "../src/translations/universalPhrases.ts");

const CAT2_PHRASES = {
  // --- Service subpages: Division 01 Business Facilitation ---
  "Compliant Market Entry": {
    en: "Compliant Market Entry",
    fr: "Entrée sur le Marché Conforme",
    pt: "Entrada no Mercado em Conformidade",
    sw: "Kuingia Sokoni kwa Kuzingatia Sheria",
    ln: "Kokota na Zando na Botosi Mibeko",
    af: "Voldoenende Marktoetrede",
    zu: "Ukungena Emakethe Ngokuhambisana Nomthetho",
    xh: "Ukungena eMarikeni Ngokuthobela Imithetho",
    zh: "合法合规市场准入",
    ar: "دخول متوافق وقانوني إلى السوق",
    es: "Entrada Conforme al Mercado",
    de: "Rechtskonformer Markteintritt",
    hi: "अनुपालन योग्य बाजार प्रवेश",
    ru: "Соответствующий нормам выход на рынок",
    ja: "コンプライアンスに準拠した市場参入",
    ko: "규정 준수 기반 시장 진입",
    it: "Ingresso sul Mercato Conforme",
    nl: "Compliante Markttoetreding",
  },
  "Clear Path to Market": {
    en: "Clear Path to Market",
    fr: "Une Voie Claire vers le Marché",
    pt: "Um Caminho Claro para o Mercado",
    sw: "Njia Wazi Kuelekea Sokoni",
    ln: "Nzela ya Polele mpo na Zando",
    af: "Duidelike Roete na die Mark",
    zu: "Indlela Ecacile Eya Emakethe",
    xh: "Indlela Ecacileyo Eya eMarikeni",
    zh: "畅通无阻的入市通道",
    ar: "مسار واضح وممهد إلى السوق",
    es: "Un Camino Claro hacia el Mercado",
    de: "Klarer Weg in den Markt",
    hi: "बाजार के लिए स्पष्ट मार्ग",
    ru: "Прямой путь на рынок",
    ja: "市場への明確なロードマップ",
    ko: "시장으로 향하는 명확한 진출로",
    it: "Un Percorso Chiaro verso il Mercato",
    nl: "Een Duidelijk Pad naar de Markt",
  },
  "Navigating corporate filings, licensing, and workforce mobility without delays.": {
    en: "Navigating corporate filings, licensing, and workforce mobility without delays.",
    fr: "Gérer les dépôts d'entreprise, les licences et la mobilité du personnel sans aucun retard.",
    pt: "Gerir registos societários, licenciamento e mobilidade de pessoal sem atrasos.",
    sw: "Kuongoza majalada ya kampuni, leseni na uhamaji wa wafanyakazi bila ucheleweshaji.",
    ln: "Kokatisa mikanda ya kompani, ndingisa mpe kotambwisa basali kozanga kowelela to bowumbu.",
    af: "Navigeer korporatiewe indienings, lisensiëring en werksmagmobiliteit sonder vertragings.",
    zu: "Ukuhamba kumafayela ezinkampani, ukuthola amalayisense, nokuhamba kwabasebenzi ngaphandle kokubambezeleka.",
    xh: "Ukuhamba kumaxwebhu enkampani, ukukhupha amaphepha-mvume, nokuhamba kwabasebenzi ngaphandle kokulibaziseka.",
    zh: "高效办理企业公司法务备案、特许牌照审批及外籍高管员工派驻调配，全程杜绝延误。",
    ar: "إنجاز الإيداعات المؤسسية، والتراخيص، وتسهيل تنقل القوى العاملة دون أي تأخير.",
    es: "Gestionar trámites corporativos, licencias y movilidad de personal sin retrasos.",
    de: "Behördengänge, Lizenzierungen und Mitarbeitermobilität zügig und verzögerungsfrei abwickeln.",
    hi: "बिना किसी देरी के कॉर्पोरेट फाइलिंग, लाइसेंसिंग और कार्यबल गतिशीलता का संचालन।",
    ru: "Быстрое оформление корпоративных документов, лицензий и организация мобильности кадров без задержек.",
    ja: "法人登記、許認可取得、現地スタッフの赴任手続きを遅延なく確実に推進。",
    ko: "기업 법인 설립, 인허가 발급 및 인력 이동을 지연 없이 신속하게 진행합니다.",
    it: "Gestione delle pratiche societarie, licenze e mobilità del personale senza ritardi.",
    nl: "Het regelen van bedrijfsindieningen, licenties en personeelsmobiliteit zonder vertraging.",
  },
  "Establishing Your Operations Safely & Compliantly": {
    en: "Establishing Your Operations Safely & Compliantly",
    fr: "Établir Vos Opérations en Toute Sécurité et Conformité",
    pt: "Estabelecer as Suas Operações com Segurança e Conformidade",
    sw: "Kuanzisha Shughuli Zako kwa Usalama na Kuzingatia Sheria",
    ln: "Kofungola Misala na Yo na Kimya mpe na Botosi Mibeko",
    af: "Vestiging van U Bedrywighede Veilig en Voldoenend",
    zu: "Ukumisa Ukusebenza Kwakho Ngokuphepha Nangokuhambisana Nomthetho",
    xh: "Ukumisa Umsebenzi Wakho Ngokukhuselekileyo Nangokuthobela Imithetho",
    zh: "安全、稳健且完全合规地设立在地实体业务",
    ar: "تأسيس عملياتك بأمان وامتثال قانوني كامل",
    es: "Establecer sus Operaciones de Forma Segura y Conforme",
    de: "Ihren Betrieb sicher und vorschriftsmäßig aufbauen",
    hi: "अपने संचालन को सुरक्षित और अनुपालन के साथ स्थापित करना",
    ru: "Безопасное и юридически безупречное развертывание вашего бизнеса",
    ja: "安全かつ法令を遵守した事業体制の確立",
    ko: "안전하고 규정에 부합하는 현지 비즈니스 운영 구축",
    it: "Avviare le Tue Operazioni in Modo Sicuro e Conforme",
    nl: "Uw Activiteiten Veilig en Compliant Opzetten",
  },
  "Entering the Democratic Republic of Congo requires clear understanding of local administrative procedures, corporate governance statutes, immigration regulations, and licensing requirements.": {
    en: "Entering the Democratic Republic of Congo requires clear understanding of local administrative procedures, corporate governance statutes, immigration regulations, and licensing requirements.",
    fr: "S'implanter en République Démocratique du Congo exige une compréhension claire des procédures administratives locales, des statuts de gouvernance d'entreprise, des règles d'immigration et des exigences en matière de licences.",
    pt: "Entrar na República Democrática do Congo requer uma compreensão clara dos procedimentos administrativos locais, estatutos de governação corporativa, regulamentos de imigração e requisitos de licenciamento.",
    sw: "Kuingia Jamhuri ya Kidemokrasia ya Kongo kunahitaji uelewa wazi wa taratibu za kiutawala za ndani, sheria za utawala wa mashirika, kanuni za uhamiaji, na mahitaji ya leseni.",
    ln: "Kokota na République Démocratique du Congo esengaka boyebi ya polele ya mitindo ya leta, mibeko ya kompani, mibeko ya bakota mboka mpe masenga ya mikanda ya ndingisa.",
    af: "Om die Demokratiese Republiek van die Kongo binne te gaan, vereis 'n duidelike begrip van plaaslike administratiewe prosedures, korporatiewe bestuurswette, immigrasieregulasies en lisensievereistes.",
    zu: "Ukungena e-Democratic Republic of Congo kudinga ukuqonda okucacile kwezinqubo zokuphatha zendawo, imithetho yokuphathwa kwezinkampani, imithetho yokufika kwabantu, nezidingo zamalayisense.",
    xh: "Ukungena kwi-Democratic Republic of Congo kufuna ukuqonda okucacileyo kweenkqubo zolawulo zendawo, imithetho yolawulo lwenkampani, imimiselo yokufika kwabantu, neemfuno zeelayisensi.",
    zh: "进军刚果民主共和国市场，必须透彻掌握当地行政办事流程、公司治理公司法准则、出入境签证移民规定以及特种行业准入牌照要求。",
    ar: "يتطلب الدخول إلى جمهورية الكونغو الديمقراطية فهماً دقيقاً للإجراءات الإدارية المحلية، وقوانين حوكمة الشركات، ولوائح الهجرة، واشتراطات التراخيص.",
    es: "Entrar en la República Democrática del Congo requiere una comprensión clara de los procedimientos administrativos locales, leyes de gobierno corporativo, normativas de inmigración y requisitos de licencias.",
    de: "Der Markteintritt in die Demokratische Republik Kongo erfordert ein klares Verständnis lokaler Verwaltungsverfahren, Corporate-Governance-Vorschriften, Einwanderungsbestimmungen und Lizenzanforderungen.",
    hi: "कांगो लोकतांत्रिक गणराज्य में प्रवेश के लिए स्थानीय प्रशासनिक प्रक्रियाओं, कॉर्पोरेट प्रशासन विधियों, आव्रजन नियमों और लाइसेंसिंग आवश्यकताओं की स्पष्ट समझ की आवश्यकता होती है।",
    ru: "Выход на рынок Демократической Республики Конго требует глубокого понимания местных административных процедур, норм корпоративного управления, миграционных правил и лицензионных требований.",
    ja: "コンゴ民主共和国への進出には、現地の行政手続き、コーポレートガバナンス法、入国管理規則、および事業認可要件に関する明確な理解が不可欠です。",
    ko: "콩고민주공화국 시장에 진입하기 위해서는 현지 행정 절차, 기업 지배구조 법률, 출입국 이민 규정 및 인허가 요건에 대한 명확한 이해가 필수적입니다.",
    it: "L'ingresso nella Repubblica Democratica del Congo richiede una chiara comprensione delle procedure amministrative locali, delle norme di governance societaria, delle normative sull'immigrazione e dei requisiti di licenza.",
    nl: "Toetreding tot de Democratische Republiek Congo vereist een duidelijk inzicht in lokale administratieve procedures, corporate governance-wetgeving, immigratieregels en vergunningseisen.",
  },
  "ARSSA’s Business Facilitation division acts as your on-the-ground administrative and regulatory compass — ensuring that from your initial feasibility study to your daily operations, your business is fully compliant and legally protected.": {
    en: "ARSSA’s Business Facilitation division acts as your on-the-ground administrative and regulatory compass — ensuring that from your initial feasibility study to your daily operations, your business is fully compliant and legally protected.",
    fr: "La division Facilitation des Affaires d'ARSSA agit comme votre boussole administrative et réglementaire sur le terrain — veillant à ce que, de votre étude de faisabilité initiale à vos opérations quotidiennes, votre entreprise soit pleinement conforme et légalement protégée.",
    pt: "A divisão de Facilitação de Negócios da ARSSA actua como a sua bússola administrativa e regulamentar no terreno — garantindo que, desde o estudo de viabilidade inicial até às operações diárias, o seu negócio esteja em total conformidade e legalmente protegido.",
    sw: "Kitengo cha Uwezeshaji Biashara cha ARSSA hufanya kazi kama dira yako ya kiutawala na kikanuni mashinani — kuhakikisha kuwa kuanzia upembuzi yakinifu wa awali hadi shughuli zako za kila siku, biashara yako inazingatia sheria kikamilifu na inalindwa kisheria.",
    ln: "Eteni ya ARSSA ya Kosalisa Mombongo ezali lokola maneti na yo ya mibeko mpe ya leta na mabele — kokeba ete banda bolukiluki ya yambo kino na misala ya mikolo nyonso, kompani na yo etosa mibeko nyonso mpe ebatelami na mibeko.",
    af: "ARSSA se Besigheidsfasiliteringsafdeling dien as u plaaslike administratiewe en regulatoriese kompas — en verseker dat vanaf u aanvanklike lewensvatbaarheidstudie tot u daaglikse bedrywighede, u besigheid ten volle voldoenend en wetlik beskerm is.",
    zu: "Uphiko lwe-ARSSA Lokugqugquzela Ibhizinisi lusebenza njengekhampasi yakho yokuphatha nokulawula endaweni — luqinisekisa ukuthi kusukela ocwaningweni lwakho lokuqala lokuthi kungenzeka yini kuze kube semisebenzini yakho yansuku zonke, ibhizinisi lakho lihambisana ngokugcwele nomthetho futhi livikelekile ngokomthetho.",
    xh: "Icandelo le-ARSSA loQuquzelelo loShishino lisebenza njengekhampasi yakho yolawulo emhlabeni — liqinisekisa ukuba ukusuka kufundo lwakho lokuqala lokwenzeka komsebenzi ukuya kwimisebenzi yakho yemihla ngemihla, ishishini lakho liyithobela ngokupheleleyo imithetho kwaye likhuselekile ngokwasemthethweni.",
    zh: "ARSSA 的商务落地促进部门充当您在刚果（金）实地的政策与行政导航指南针 —— 确保从最初的可行性论证到日常长效运营，您的企业始终合规完备并受到法律充分保护。",
    ar: "يعمل قسم تيسير الأعمال في ARSSA كبوصلة إدارية وتنظيمية ميدانية لك — لضمان امتثال عملك وحمايته قانونياً بالكامل بدءاً من دراسة الجدوى الأولى وحتى العمليات اليومية المستمرة.",
    es: "La división de Facilitación de Negocios de ARSSA actúa como su brújula administrativa y regulatoria en el terreno, garantizando que, desde su estudio de viabilidad inicial hasta sus operaciones diarias, su negocio cumpla plenamente y esté legalmente protegido.",
    de: "Der Geschäftsbereich Business Facilitation von ARSSA fungiert als Ihr administrativer und regulatorischer Kompass vor Ort — und stellt sicher, dass Ihr Unternehmen von der ersten Machbarkeitsstudie bis zum Tagesgeschäft vollkommen konform und rechtlich geschützt ist.",
    hi: "ARSSA का बिजनेस फैसिलिटेशन डिवीजन आपके ऑन-द-ग्राउंड प्रशासनिक और विनियामक कंपास के रूप में कार्य करता है — यह सुनिश्चित करता है कि आपके शुरुआती व्यवहार्यता अध्ययन से लेकर आपके दैनिक कार्यों तक, आपका व्यवसाय पूरी तरह से अनुपालन और कानूनी रूप से संरक्षित है।",
    ru: "Подразделение фасилитации бизнеса ARSSA выступает вашим административным и нормативным компасом на местах — гарантируя, что от первичного анализа до текущей операционной деятельности ваш бизнес полностью соответствует закону и юридически защищен.",
    ja: "ARSSA の事業円滑化部門は、現地の行政・法規制における頼れる羅針盤として機能し、初期の実現可能性調査から日常のオペレーションに至るまで、貴社のビジネスが完全なコンプライアンスを保ち、法的に手厚く保護されるよう徹底します。",
    ko: "ARSSA의 비즈니스 촉진 부문은 귀사의 현지 행정 및 규제 나침반 역할을 수행하여, 초기 타당성 조사부터 일상적인 운영에 이르기까지 귀사의 비즈니스가 규정을 완벽히 준수하고 법적으로 보호받도록 보장합니다.",
    it: "La divisione Facilitazione d'Impresa di ARSSA funge da bussola amministrativa e normativa sul campo, garantendo che, dallo studio di fattibilità iniziale alle operazioni quotidiane, la tua attività sia pienamente conforme e legalmente protetta.",
    nl: "De divisie Business Facilitation van ARSSA fungeert als uw administratieve en regelgevende kompas ter plaatse — en zorgt ervoor dat uw bedrijf van de eerste haalbaarheidsstudie tot de dagelijkse werkzaamheden volledig compliant en juridisch beschermd is.",
  },
  "Reduce administrative friction and establish compliant, well-prepared operations in the DRC.": {
    en: "Reduce administrative friction and establish compliant, well-prepared operations in the DRC.",
    fr: "Réduire les frictions administratives et établir des opérations conformes et bien préparées en RDC.",
    pt: "Reduzir o atrito administrativo e estabelecer operações em conformidade e bem preparadas na RDC.",
    sw: "Punguza vikwazo vya kiutawala na kuanzisha shughuli zinazozingatia sheria na zilizojiandaa vyema nchini DRC.",
    ln: "Kokitisa mitungisi ya mikanda ya leta mpe kofungola misala oyo etosaka mibeko mpe ebongisami malamu na RDC.",
    af: "Verminder administratiewe wrywing en vestig voldoenende, goed voorbereide bedrywighede in die DRK.",
    zu: "Nciphisa ukungqubuzana kokuphatha futhi umise ukusebenza okuhambisana nomthetho, okulungiselelwe kahle e-DRC.",
    xh: "Nciphisa ukungquzulana kolawulo kwaye umise imisebenzi ethobela imithetho, elungiselelwe kakuhle e-DRC.",
    zh: "消除行政审批摩擦阻力，在刚果（金）建立合规完备、准备充分的高标准业务运营。",
    ar: "تقليل العقبات الإدارية وتأسيس عمليات متوافقة ومُعدة باحترافية في جمهورية الكونغو الديمقراطية.",
    es: "Reducir la fricción administrativa y establecer operaciones conformes y bien preparadas en la RDC.",
    de: "Administrativen Aufwand minimieren und rechtskonforme, bestens vorbereitete Abläufe in der DR Kongo etablieren.",
    hi: "प्रशासनिक घर्षण को कम करें और डीआरसी में अनुपालन, अच्छी तरह से तैयार संचालन स्थापित करें।",
    ru: "Свести к минимуму бюрократическое сопротивление и запустить безупречно подготовленный бизнес в ДРК.",
    ja: "行政上の摩擦を低減し、コンゴ民主共和国において法令を遵守した万全な事業基盤を確立します。",
    ko: "행정적 마찰을 최소화하고 콩고민주공화국에서 규정을 철저히 준수하는 철저히 준비된 사업을 구축합니다.",
    it: "Ridurre gli attriti amministrativi e stabilire operazioni conformi e ben preparate nella RDC.",
    nl: "Verminder administratieve belemmeringen en zet conforme, goed voorbereide activiteiten op in de DRC.",
  },

  // --- Division 02 Market Growth ---
  "Commercial Traction": {
    en: "Commercial Traction",
    fr: "Traction Commerciale",
    pt: "Tracção Comercial",
    sw: "Uvutano wa Kibiashara",
    ln: "Bokoli ya Solo ya Mombo",
    af: "Kommersiële Vastrap",
    zu: "Ukudonsa Kwezohwebo",
    xh: "Ukutsala Kwezorhwebo",
    zh: "商业规模化动销",
    ar: "الزخم والنمو التجاري",
    es: "Tracción Comercial",
    de: "Kommerzielle Zugkraft",
    hi: "वाणिज्यिक आकर्षण",
    ru: "Коммерческая динамика и продажи",
    ja: "商業的トラクション（販売拡大）",
    ko: "실질적인 상업적 견인력",
    it: "Trazione Commerciale",
    nl: "Commerciële Tractie",
  },
  "From Placement to Offtake": {
    en: "From Placement to Offtake",
    fr: "Du Placement à l'Écoulement",
    pt: "Da Colocação ao Escoamento",
    sw: "Kutoka Kuweka Bidhaa hadi Mauzo Halisi",
    ln: "Banda na Kotiya Biloko kino na Koteka Yango",
    af: "Van Plasing tot Afset",
    zu: "Kusuka Ekubekweni Kuya Ekuthengisweni",
    xh: "Ukusuka eKufakweni kuye eKuthengisweni",
    zh: "从货架铺货到持续承销出货",
    ar: "من العرض إلى تصريف المبيعات الفعلي",
    es: "De la Colocación a la Venta",
    de: "Von der Platzierung bis zum Abverkauf",
    hi: "प्लेसमेंट से लेकर ऑफ-टेक तक",
    ru: "От выкладки товара до устойчивого сбыта",
    ja: "店舗配荷から実売・リピート受注まで",
    ko: "제품 입점에서 지속적인 실판매 창출까지",
    it: "Dal Posizionamento alla Vendita Effettiva",
    nl: "Van Schapplaatsing tot Daadwerkelijke Afzet",
  },
  "Driving real consumer demand and dependable wholesale distribution pipelines.": {
    en: "Driving real consumer demand and dependable wholesale distribution pipelines.",
    fr: "Stimuler une véritable demande des consommateurs et des canaux de distribution en gros fiables.",
    pt: "Estimular a procura real dos consumidores e canais fiáveis de distribuição grossista.",
    sw: "Kuchochea mahitaji halisi ya watumiaji na mifereji ya usambazaji wa jumla inayotegemewa.",
    ln: "Kotinda basombi balinga biloko na yo ya solo mpe kotonga banzela ya koteka biloko na bagrossistes ya kotyela motema.",
    af: "Dryf werklike verbruikersvraag en betroubare groothandelverspreidingspyplyne aan.",
    zu: "Ukugqugquzela isidingo sangempela sabathengi namaphayiphu athembekile okusabalalisa ezitolo ezinkulu.",
    xh: "Ukuqhuba imfuno yokwenene yabathengi nemibhobho ethembekileyo yokusasaza kwiivenkile ezinkulu.",
    zh: "全面拉动终端真实消费需求，构建稳定可持续的各级批发分销输送管道。",
    ar: "تحفيز طلب المستهلكين الحقيقي وبناء قنوات توزيع موثوقة بالجملة.",
    es: "Impulsar la demanda real de los consumidores y canales confiables de distribución mayorista.",
    de: "Echte Kundennachfrage generieren und verlässliche Großhandelsvertriebskanäle aufbauen.",
    hi: "वास्तविक उपभोक्ता मांग और भरोसेमंद थोक वितरण पाइपलाइनों को आगे बढ़ाना।",
    ru: "Формирование реального потребительского спроса и построение надежных оптовых каналов сбыта.",
    ja: "真の消費者需要を喚起し、信頼できる卸売流通パイプラインを確立します。",
    ko: "실질적인 소비자 수요를 창출하고 신뢰할 수 있는 도매 유통 파이프라인을 구축합니다.",
    it: "Guidare la reale domanda dei consumatori e costruire canali affidabili di distribuzione all'ingrosso.",
    nl: "Het stimuleren van echte consumentenvraag en het opbouwen van betrouwbare groothandelsdistributiekanalen.",
  },
  "Transforming Brand Presence into Commercial Offtake": {
    en: "Transforming Brand Presence into Commercial Offtake",
    fr: "Transformer la Présence de Marque en Ventes Commerciales",
    pt: "Transformar a Presença da Marca em Vendas Comerciais",
    sw: "Kubadilisha Uwepo wa Chapa Kuwa Mauzo Halisi ya Kibiashara",
    ln: "Kobongola Lokumu ya Marque na yo ekomisa Koteka Biloko na Bozwi Mbongo",
    af: "Omskep Handelsmerkaanwesigheid in Kommersiële Afset",
    zu: "Ukuguqula Ukuba Khona Komkhiqizo Kube Ukuthengiswa Kwezohwebo",
    xh: "Ukuguqula Ubukho Be-Brand Kube Kukuthengiswa Kwezorhwebo",
    zh: "将品牌声量切实转化为源源不断的商业出货订单",
    ar: "تحويل حضور العلامة التجارية إلى مبيعات تجارية مستدامة",
    es: "Transformar la Presencia de Marca en Ventas Comerciales Reales",
    de: "Markenpräsenz in nachhaltigen kommerziellen Absatz verwandeln",
    hi: "ब्रांड उपस्थिति को वाणिज्यिक ऑफ-टेक में बदलना",
    ru: "Трансформация узнаваемости бренда в реальные коммерческие продажи",
    ja: "ブランド認知度を実質的な販売実績・売上へと転換",
    ko: "브랜드 인지도를 실질적인 상업적 매출로 전환",
    it: "Trasformare la Presenza del Marchio in Vendite Commerciali Effettive",
    nl: "Merkbekendheid omzetten in structurele commerciële afzet",
  },
  "Gaining shelf presence is only half the battle. In competitive and fast-evolving markets like Lubumbashi and Kinshasa, products need continuous brand resonance, strong distributor alignment, and active demand generation.": {
    en: "Gaining shelf presence is only half the battle. In competitive and fast-evolving markets like Lubumbashi and Kinshasa, products need continuous brand resonance, strong distributor alignment, and active demand generation.",
    fr: "Obtenir une présence en rayon n'est que la moitié de la bataille. Dans des marchés concurrentiels et en évolution rapide comme Lubumbashi et Kinshasa, les produits ont besoin d'une résonance continue de la marque, d'un alignement fort des distributeurs et d'une génération active de la demande.",
    pt: "Conquistar espaço nas prateleiras é apenas metade da batalha. Em mercados competitivos e em rápida evolução como Lubumbashi e Kinshasa, os produtos precisam de ressonância contínua da marca, forte alinhamento com distribuidores e geração activa de procura.",
    sw: "Kupata nafasi kwenye rafu ni nusu tu ya vita. Katika masoko yenye ushindani na yanayobadilika haraka kama Lubumbashi na Kinshasa, bidhaa zinahitaji mwonekano endelevu wa chapa, ushirikiano dhabiti wa wasambazaji, na uundaji thabiti wa mahitaji.",
    ln: "Kotiya biloko na bitanda ya magazini ezali kaka katikati ya bitumba. Na bazando ya kowelela mpe oyo ezali kobongwana noki lokola Lubumbashi mpe Kinshasa, biloko esengeli bato bayeba yango tango nyonso, boyokani makasi na bagrossistes mpe kobimisa mposa ya kosomba epai ya bato.",
    af: "Om raakplek op rakke te kry is slegs die helfte van die stryd. In mededingende en vinnig veranderende markte soos Lubumbashi en Kinshasa, benodig produkte deurlopende handelsmerkweerklank, sterk verspreidersbelyning en aktiewe vraagskepping.",
    zu: "Ukuthola ukubekwa emashalofini kuyingxenye nje yempi. Ezimakethe ezinokuncintisana neziguquka ngokushesha njengeLubumbashi neKinshasa, imikhiqizo idinga ukuzwakala okuqhubekayo komkhiqizo, ukuvumelana okuqinile kwabasabalalisi, nokwakha isidingo okusebenzayo.",
    xh: "Ukufumana indawo kwiishelfu sisiqingatha nje sedabi. Kwiimarike ezikhuphisanayo nezikhula ngokukhawuleza njengeLubumbashi neKinshasa, iimveliso zidinga ukungqinelana okuqhubekayo kwe-brand, ulungelelwaniso oluqinileyo lwabasasazi, nokuvuselelwa okusebenzayo kwemfuno.",
    zh: "获得终端货架陈列仅仅成功了一半。在卢本巴希与金沙萨等竞争激烈且飞速演进的商业重镇，产品更需要持久的品牌认知度、分销商渠道的高度利益协同以及持续主动的终端需求拉动。",
    ar: "إن الحصول على مساحة عرض في المتاجر هو نصف المعركة فقط. في الأسواق التنافسية سريعة التطور مثل لوبومباشي وكينشاسا، تحتاج المنتجات إلى صدى مستمر للعلامة التجارية، وتوافق قوي مع الموزعين، وتوليد نشط للطلب.",
    es: "Obtener presencia en las estanterías es solo la mitad de la batalla. En mercados competitivos y de rápida evolución como Lubumbashi y Kinshasa, los productos necesitan una resonancia de marca continua, una sólida alineación con distribuidores y una generación activa de demanda.",
    de: "Präsenz im Verkaufsregal ist nur die halbe Miete. In wettbewerbsintensiven und dynamischen Märkten wie Lubumbashi und Kinshasa benötigen Produkte kontinuierliche Markenresonanz, enge Händleranbindung und aktive Nachfragegenerierung.",
    hi: "शेल्फ उपस्थिति प्राप्त करना केवल आधी लड़ाई है। लुबुम्बाशी और किंशासा जैसे प्रतिस्पर्धी और तेजी से विकसित हो रहे बाजारों में, उत्पादों को निरंतर ब्रांड अनुनाद, मजबूत वितरक संरेखण और सक्रिय मांग निर्माण की आवश्यकता होती है।",
    ru: "Попасть на полки магазинов — лишь половина дела. На таких конкурентных и быстро развивающихся рынках, как Лубумбаши и Киншаса, товарам необходимы постоянная узнаваемость, четкая работа дистрибьюторов и активное стимулирование спроса.",
    ja: "店頭の棚を確保することは戦いの半分にすぎません。ルブンバシやキンシャサのような競争が激しく急速に変化する市場では、持続的なブランド訴求力、強固な代理店連携、能動的な需要創出が不可欠です。",
    ko: "매대에 제품을 올리는 것은 절반의 성공일 뿐입니다. 루붐바시, 킨샤사와 같이 경쟁이 치열하고 빠르게 진화하는 시장에서는 지속적인 브랜드 인지도, 유통업체와의 긴밀한 파트너십 및 적극적인 수요 창출이 필수적입니다.",
    it: "Ottenere visibilità sugli scaffali è solo metà dell'opera. In mercati competitivi e in rapida evoluzione come Lubumbashi e Kinshasa, i prodotti necessitano di una costante risonanza del marchio, forte allineamento con i distributori e generazione attiva della domanda.",
    nl: "Een plek in het schap veroveren is slechts het halve werk. In concurrerende en snel evoluerende markten zoals Lubumbashi en Kinshasa hebben producten continue merkresonantie, een sterke afstemming met distributeurs en actieve vraagcreatie nodig.",
  },
  "ARSSA connects South African (SADAC) brands directly with vetted wholesalers, retailers, and commercial buyers, orchestrating promotions and distribution channels that deliver repeatable revenue.": {
    en: "ARSSA connects South African (SADAC) brands directly with vetted wholesalers, retailers, and commercial buyers, orchestrating promotions and distribution channels that deliver repeatable revenue.",
    fr: "ARSSA met directement en relation les marques sud-africaines (SADAC) avec des grossistes, détaillants et acheteurs commerciaux vérifiés, orchestrant des promotions et des canaux de distribution qui génèrent des revenus récurrents.",
    pt: "A ARSSA liga directamente as marcas sul-africanas (SADAC) a grossistas, retalhistas e compradores comerciais verificados, orquestrando promoções e canais de distribuição que geram receitas recorrentes.",
    sw: "ARSSA inaunganisha chapa za Afrika Kusini (SADAC) moja kwa moja na wauzaji wa jumla, wauzaji wa rejareja na wanunuzi wa kibiashara walioidhinishwa, ikiratibu matangazo na njia za usambazaji zinazoleta mapato endelevu.",
    ln: "ARSSA ezali kokangisa bakompani ya Afríka ya Súdi (SADAC) mbala moko na bagrossistes, babagazini mpe basombi minene ya solo, kobongisa bansango ya mombo mpe banzela ya kokaba biloko oyo ezali kopesa mbongo mikolo nyonso.",
    af: "ARSSA verbind Suid-Afrikaanse (SADAC) handelsmerke direk met gekeurde groothandelaars, kleinhandelaars en kommersiële kopers, en orkestreer promosies en verspreidingskanale wat herhaalbare inkomste lewer.",
    zu: "I-ARSSA ixhuma imikhiqizo yaseNingizimu Afrika (SADAC) ngqo nabathengisi bezitolo ezinkulu abahloliwe, abathengisi bezitolo, nabathengi bezohwebo, ihlele ukukhushulwa neziteshi zokusabalalisa eziletha imali engenayo ephindaphindayo.",
    xh: "I-ARSSA iqhagamshela ii-brands zaseMzantsi Afrika (SADAC) ngokuthe ngqo nabathengisi beevenkile ezinkulu abavavanyiweyo, abathengisi, nabathengi bezorhwebo, iququzelela amaphulo okwazisa namajelo okusasaza azisa ingeniso ephindaphindwayo.",
    zh: "ARSSA 将南非（SADAC）优质品牌直接引荐给经过资格审查的刚果（金）大型批发商、连锁零售商与大宗商业买家，策划执行全套联合促销与渠道建设，实现长期稳定的商业复购与盈利回报。",
    ar: "تربط ARSSA العلامات التجارية من جنوب أفريقيا (SADAC) مباشرة بتجار الجملة والتجزئة والمشترين التجاريين المعتمدين، مع تنظيم الحملات الترويجية وقنوات التوزيع لتحقيق إيرادات متكررة ومستدامة.",
    es: "ARSSA conecta las marcas sudafricanas (SADAC) directamente con mayoristas, minoristas y compradores comerciales verificados, organizando promociones y canales de distribución que generan ingresos recurrentes.",
    de: "ARSSA verbindet südafrikanische (SADAC) Marken direkt mit geprüften Großhändlern, Einzelhändlern und gewerblichen Einkäufern und steuert Promotionen sowie Vertriebskanäle für wiederkehrende Umsätze.",
    hi: "ARSSA दक्षिण अफ्रीकी (SADAC) ब्रांडों को सीधे जांचे-परखे थोक विक्रेताओं, खुदरा विक्रेताओं और वाणिज्यिक खरीदारों से जोड़ता है, प्रचार और वितरण चैनलों का आयोजन करता है जो दोहराए जाने वाले राजस्व प्रदान करते हैं।",
    ru: "ARSSA напрямую связывает бренды из Южной Африки (SADAC) с проверенными оптовиками, розничными сетями и корпоративными покупателями, выстраивая промокампании и каналы сбыта для получения стабильной регулярной выручки.",
    ja: "ARSSA は、南アフリカ（SADAC）のブランドを審査済みの卸売業者、小売業者、商業バイヤーと直接結びつけ、持続的・反復的な収益を生み出すプロモーションと流通チャネルを構築・推進します。",
    ko: "ARSSA는 남아공(SADAC) 브랜드를 검증된 현지 도매상, 소매점 및 상업 바이어와 직접 연결하고, 지속적인 반복 매출을 창출하는 프로모션과 유통 채널을 유기적으로 기획·실행합니다.",
    it: "ARSSA collega i marchi sudafricani (SADAC) direttamente con grossisti, rivenditori e acquirenti commerciali verificati, orchestrando promozioni e canali di distribuzione che generano entrate continuative.",
    nl: "ARSSA brengt Zuid-Afrikaanse (SADAC) merken rechtstreeks in contact met gescreende groothandelaren, retailers en commerciële inkopers, en structureert promoties en distributiekanalen die zorgen voor herhaalbare omzet.",
  },

  // --- Division 03 Import Export ---
  "Corridor Trade": {
    en: "Corridor Trade",
    fr: "Commerce du Corridor",
    pt: "Comércio no Corredor",
    sw: "Biashara ya Korido",
    ln: "Mombo na Nzela ya Corridor",
    af: "Korridorhandel",
    zu: "Uhwebo Lwephasishi",
    xh: "Urhwebo Lwephasishi",
    zh: "走廊跨国进出口贸易",
    ar: "تجارة ممر التبادل التجاري",
    es: "Comercio en el Corredor",
    de: "Korridor-Handel",
    hi: "गलियारा व्यापार",
    ru: "Торговля в коридоре",
    ja: "回廊貿易ビジネス",
    ko: "회랑 무역 비즈니스",
    it: "Commercio lungo il Corridoio",
    nl: "Corridorhandel",
  },
  "Compliant Cargo Movement": {
    en: "Compliant Cargo Movement",
    fr: "Mouvement de Fret Conforme",
    pt: "Movimentação de Carga em Conformidade",
    sw: "Usafirishaji wa Mizigo Unaofuata Sheria",
    ln: "Kotambwisa Biloko na Botosi ya Mibeko",
    af: "Voldoenende Vragbeweging",
    zu: "Ukuhamba Kwempahla Ngokuhambisana Nomthetho",
    xh: "Ukuhamba Kweempahla Ngokuthobela Imithetho",
    zh: "合规货运通关与流转",
    ar: "حركة شحن بضائع قانونية ومتوافقة",
    es: "Movimiento de Carga Conforme",
    de: "Rechtskonformer Gütertransport",
    hi: "अनुपालन योग्य कार्गो आंदोलन",
    ru: "Грузоперевозки в строгом соответствии с нормами",
    ja: "コンプライアンス遵守の貨物輸送",
    ko: "규정 준수 기반 화물 운송",
    it: "Movimentazione Merci Conforme",
    nl: "Conforme Vrachtbeweging",
  },
  "Eliminating customs bottlenecks, demurrage costs, and documentation errors.": {
    en: "Eliminating customs bottlenecks, demurrage costs, and documentation errors.",
    fr: "Éliminer les goulots d'étranglement douaniers, les frais de surestaries et les erreurs documentaires.",
    pt: "Eliminar estrangulamentos aduaneiros, custos de sobrestadia e erros documentais.",
    sw: "Kuondoa vikwazo vya forodha, gharama za kuchelewesha mizigo bandarini, na makosa ya hati.",
    ln: "Kolongola mikakatano na duane, bafacture ya kowelela biloko na libongo mpe mabunga ya mikanda.",
    af: "Uitskakeling van doeaneknelpunte, staangeldkoste en dokumentasiefoute.",
    zu: "Ukuqeda izingqinamba zamasiko, izindleko zokubambezeleka kwempahla, namaphutha emibhalo.",
    xh: "Ukuphelisa imiqobo yamasiko, iindleko zokulibaziseka kwempahla, neziphoso zamaxwebhu.",
    zh: "消除海关卡点瓶颈、降低滞期堆存巨额额外成本并杜绝单证文件申报疏漏。",
    ar: "القضاء على اختناقات الجمارك، وتكاليف رسوم التأخير (الأرضيات)، والأخطاء في المستندات.",
    es: "Eliminar cuellos de botella aduaneros, costos de sobrestadía y errores de documentación.",
    de: "Zollengpässe, Standgeldkosten und Dokumentationsfehler konsequent vermeiden.",
    hi: "सीमा शुल्क बाधाओं, डिमरेज लागत और दस्तावेज़ीकरण त्रुटियों को समाप्त करना।",
    ru: "Ликвидация таможенных заторов, штрафов за простой и ошибок в документации.",
    ja: "通関時のボトルネック、超過保管料（デマレージ）、書類の不備・エラーを徹底排除。",
    ko: "통관 병목 현상, 체선료/지체료 발생 및 서류 작성 오류를 원천 차단합니다.",
    it: "Eliminare i colli di bottiglia doganali, i costi di controstallia e gli errori documentali.",
    nl: "Het elimineren van douane-knelpunten, overliggelden en documentatiefouten.",
  },
  "End-to-End Trade Execution Across Borders": {
    en: "End-to-End Trade Execution Across Borders",
    fr: "Exécution Commerciale de Bout en Bout à Travers les Frontières",
    pt: "Execução Comercial de Ponta a Ponta Através das Fronteiras",
    sw: "Utekelezaji Kamili wa Biashara Mipakani",
    ln: "Kosala Mombo Mobimba Banda Ebandeli kino Suka na Kokata Bandelo",
    af: "End-tot-end Handelsuitvoering Oor Grense Heen",
    zu: "Ukwenziwa Kwezohwebo Kusukela Ekuqaleni Kuya Ekugcineni Emazweni Ahlukene",
    xh: "Ukwenziwa Korhwebo Ukusuka eKuqaleni kuye eKugqibeleni Kumanqanaba Onke Omda",
    zh: "端到端跨境贸易全程闭环执行",
    ar: "تنفيذ تجاري متكامل عبر الحدود من البداية إلى النهاية",
    es: "Ejecución Comercial de Extremo a Extremo a través de Fronteras",
    de: "Grenzüberschreitende Handelsabwicklung von A bis Z",
    hi: "सीमा पार एंड-टू-एंड व्यापार निष्पादन",
    ru: "Трансграничное исполнение торговых сделок «под ключ»",
    ja: "国境を越えたエンドツーエンドの貿易執行体制",
    ko: "국경을 넘나드는 엔드투엔드 무역 실행",
    it: "Esecuzione Commerciale End-to-End attraverso le Frontiere",
    nl: "End-to-end Handelsuitvoering over Grenzen Heen",
  },
  "Moving goods between South Africa (SADAC) and the DRC involves complex customs regulations, multi-modal transport handoffs, import certifications, and strict documentary checks.": {
    en: "Moving goods between South Africa (SADAC) and the DRC involves complex customs regulations, multi-modal transport handoffs, import certifications, and strict documentary checks.",
    fr: "Le transport de marchandises entre l'Afrique du Sud (SADAC) et la RDC implique des réglementations douanières complexes, des transferts de transport multimodaux, des certifications d'importation et des contrôles documentaires stricts.",
    pt: "A movimentação de mercadorias entre a África do Sul (SADAC) e a RDC envolve regulamentos aduaneiros complexos, transferências de transporte multimodal, certificações de importação e controlos documentais rigorosos.",
    sw: "Kusafirisha bidhaa kati ya Afrika Kusini (SADAC) na DRC kunahusisha kanuni ngumu za forodha, uhamishaji wa usafiri wa njia mbalimbali, vyeti vya uagizaji, na ukaguzi mkali wa nyaraka.",
    ln: "Kotambwisa biloko kati ya Afríka ya Súdi (SADAC) mpe RDC esengaka kotosana na mibeko ya mindondo ya duane, kopesana biloko na mituka to mpepo, mikanda ya ndingisa ya komeme biloko mpe kotala mikanda na keba nyonso.",
    af: "Die verskuiwing van goedere tussen Suid-Afrika (SADAC) en die DRK behels komplekse doeaneregulasies, multimodale vervoeroordragte, invoersertifiseringe en streng dokumentêre kontroles.",
    zu: "Ukuthutha impahla phakathi kweNingizimu Afrika (SADAC) ne-DRC kuhilela imithetho eyinkimbinkimbi yamasiko, ukudluliswa kwezithuthi ngezindlela eziningi, izitifiketi zokungenisa izwe, nokuhlolwa okuqinile kwemibhalo.",
    xh: "Ukuhambisa iimpahla phakathi koMzantsi Afrika (SADAC) ne-DRC kubandakanya imimiselo yamasiko enzima, unikezelo lwezothutho lweendidi ezininzi, iziqinisekiso zokungenisa kwelinye ilizwe, nokuhlolwa okuqinileyo kwamaxwebhu.",
    zh: "在南非（SADAC）与刚果（金）之间调运流转物资，涉及极其繁琐的海关关税法规、多式联运中转接驳、各品类进口商检强制认证以及严格无误的单证合规审查。",
    ar: "تتضمن حركة البضائع بين جنوب أفريقيا (SADAC) وجمهورية الكونغو الديمقراطية لوائح جمركية معقدة، ونقاط تسليم للنقل متعدد الوسائط، وشهادات استيراد، وفحوصات صارمة للمستندات.",
    es: "Mover mercancías entre Sudáfrica (SADAC) y la RDC implica regulaciones aduaneras complejas, transferencias de transporte multimodal, certificaciones de importación y estrictas revisiones documentales.",
    de: "Der Warentransport zwischen Südafrika (SADAC) und der DR Kongo erfordert die Navigation durch komplexe Zollvorschriften, multimodale Transportübergaben, Importzertifizierungen und strenge Dokumentenkontrollen.",
    hi: "दक्षिण अफ्रीका (SADAC) और DRC के बीच माल ले जाने में जटिल सीमा शुल्क नियम, मल्टी-मॉडल परिवहन हैंडऑफ़, आयात प्रमाणपत्र और सख्त दस्तावेजी जांच शामिल हैं।",
    ru: "Перемещение грузов между Южной Африкой (SADAC) и ДРК сопряжено со сложными таможенными регламентами, стыковкой мультимодальных перевозок, сертификацией импорта и строгим аудитом документов.",
    ja: "南アフリカ（SADAC）とコンゴ民主共和国の間での物資の輸送には、複雑な通関規制、複合一貫輸送の引き継ぎ、輸入認証の取得、厳格な書類審査が伴います。",
    ko: "남아공(SADAC)과 콩고민주공화국 간의 물품 이동에는 복잡한 관세 규정, 복합 운송 연계, 수입 인증 취득 및 엄격한 서류 심사가 수반됩니다.",
    it: "Il trasporto di merci tra il Sudafrica (SADAC) e la RDC comporta complesse normative doganali, passaggi di trasporto multimodale, certificazioni di importazione e rigorosi controlli documentali.",
    nl: "Het vervoer van goederen tussen Zuid-Afrika (SADAC) en de DRC brengt complexe douaneregels, multimodale transportoverdrachten, invoercertificeringen en strenge documentcontroles met zich mee.",
  },
  "ARSSA oversees the entire supply chain — managing tariff classifications, freight forwarding, customs clearance, and local receiving to ensure your shipments arrive on schedule, fully compliant, and within budget.": {
    en: "ARSSA oversees the entire supply chain — managing tariff classifications, freight forwarding, customs clearance, and local receiving to ensure your shipments arrive on schedule, fully compliant, and within budget.",
    fr: "ARSSA supervise l'ensemble de la chaîne d'approvisionnement — gérant le classement tarifaire, le transit, le dédouanement et la réception locale pour garantir que vos expéditions arrivent à temps, en toute conformité et dans le respect du budget.",
    pt: "A ARSSA supervisiona toda a cadeia de abastecimento — gerindo classificações pautais, transitários, desembaraço aduaneiro e recepção local para garantir que as suas remessas cheguem no prazo, em total conformidade e dentro do orçamento.",
    sw: "ARSSA inasimamia mnyororo mzima wa ugavi — kusimamia uainishaji wa ushuru wa forodha, usafirishaji wa mizigo, kibali cha forodha na mapokezi ya ndani ili kuhakikisha usafirishaji wako unafika kwa wakati, unafuata sheria kikamilifu na ndani ya bajeti.",
    ln: "ARSSA ezali kokamba banzela nyonso ya biloko — kotala motango ya mpako ya duane, kotinda biloko, kokata duane mpe kozwa biloko na esika ya kokoma mpo biloko na yo ekoma na tango, etosa mibeko nyonso mpe ekatisa te motuya ya mbongo oyo obongisaki.",
    af: "ARSSA hou toesig oor die hele voorsieningsketting — bestuur tariefklassifikasies, vragversending, doeane-uitklaring en plaaslike ontvangs om te verseker dat u besendings op skedule, ten volle voldoenend en binne begroting arriveer.",
    zu: "I-ARSSA yengamela lonke uchungechunge lokuhlinzeka — iphatha ukuhlukaniswa kwentela, ukuthunyelwa kwempahla, ukukhishwa kwempahla kumasiko, nokwamukelwa kwendawo ukuqinisekisa ukuthi izimpahla zakho zifika ngesikhathi, zihambisana ngokugcwele nomthetho, futhi zilingana nesabelomali.",
    xh: "I-ARSSA yongamela lonke uthungelwano lokubonelela — ilawula ukuhlelwa kweerhafu, ukuthunyelwa kwempahla, ukucocwa kwamasiko, nokwamkelwa kwendawo ukuqinisekisa ukuba iimpahla zakho zifika ngexesha, zithobele imithetho ngokupheleleyo, kwaye zikuhlahlo-lwabiwo mali.",
    zh: "ARSSA 实施全程供应链监控统筹 —— 精准核算 HS 海关编码归类、全程干线货代承运、口岸通关报验与目的地本地仓储签收，全力确保货物如期准点送达、法规合规完备且全程支出严控在预算之内。",
    ar: "تشرف ARSSA على سلسلة التوريد بأكملها — حيث تدير التصنيفات الجمركية، وشحن البضائع، والتخليص الجمركي، والاستلام المحلي لضمان وصول شحناتك في الموعد المحدد، وبامتثال كامل، ووفق الميزانية.",
    es: "ARSSA supervisa toda la cadena de suministro: gestiona clasificaciones arancelarias, transporte de carga, despacho de aduanas y recepción local para garantizar que sus envíos lleguen a tiempo, en pleno cumplimiento y dentro del presupuesto.",
    de: "ARSSA überwacht die gesamte Lieferkette — von der Zolltarif-Klassifizierung und Spedition über die Zollabfertigung bis zur Warenannahme vor Ort, damit Ihre Lieferungen pünktlich, vorschriftsmäßig und im Budgetrahmen eintreffen.",
    hi: "ARSSA संपूर्ण आपूर्ति श्रृंखला की देखरेख करता है — टैरिफ वर्गीकरण, फ्रेट अग्रेषण, सीमा शुल्क निकासी और स्थानीय प्राप्त करने का प्रबंधन करता है ताकि यह सुनिश्चित हो सके कि आपके शिपमेंट समय पर, पूरी तरह से अनुपालन और बजट के भीतर पहुंचें।",
    ru: "ARSSA контролирует всю цепочку поставок: правильную классификацию ТН ВЭД, экспедирование, таможенную очистку и приемку на складах в ДРК — гарантируя прибытие грузов строго по графику, в рамках закона и без перерасхода бюджета.",
    ja: "ARSSA はサプライチェーン全体を統括管理します。関税分類、国際貨物輸送、通関手続き、現地での検収・荷受けまでを一括代行し、期日通りの納品、完全な法令遵守、予算内での確実な輸送を実現します。",
    ko: "ARSSA는 관세 품목 분류, 국제 화물 운송, 세관 통관 및 현지 입고 관리에 이르기까지 공급망 전 과정을 총괄하여 귀사의 화물이 정해진 일정과 예산 내에서 규정을 완벽히 준수하며 도착하도록 보장합니다.",
    it: "ARSSA supervisiona l'intera catena di fornitura, gestendo classificazioni tariffarie, spedizioni, sdoganamento e ricezione locale per garantire che le tue spedizioni arrivino nei tempi previsti, in totale conformità e nel rispetto del budget.",
    nl: "ARSSA houdt toezicht op de complete toeleveringsketen — van tariefclassificatie en vrachtexpeditie tot inklaring en lokale goederenontvangst, zodat uw zendingen tijdig, compliant en binnen budget arriveren.",
  },

  // --- Division 04 Mining & Resources ---
  "Focused support": {
    en: "Focused support",
    fr: "Soutien Ciblé",
    pt: "Apoio Focado",
    sw: "Usaidizi Unaolenga",
    ln: "Lisalisi ya Sikisiki",
    af: "Gefokusde Ondersteuning",
    zu: "Ukusekelwa Okugxilile",
    xh: "Inkxaso Ejolisiweyo",
    zh: "矿业资源专属赋能",
    ar: "دعم متخصص ومركز",
    es: "Soporte Enfocado",
    de: "Zielgerichtete Unterstützung",
    hi: "केंद्रित सहायता",
    ru: "Целевая отраслевая поддержка",
    ja: "鉱業・資源分野に特化した支援",
    ko: "광업 및 자원 분야 맞춤형 지원",
    it: "Supporto Mirato",
    nl: "Gerichte Ondersteuning",
  },
  "Connecting opportunity with dependable execution": {
    en: "Connecting opportunity with dependable execution",
    fr: "Relier les opportunités à une exécution fiable",
    pt: "Ligar oportunidades a uma execução fiável",
    sw: "Kuunganisha fursa na utekelezaji unaotegemewa",
    ln: "Kokangisa mabaku ya mombo na mosala ya solo ya kotyela motema",
    af: "Verbind geleenthede met betroubare uitvoering",
    zu: "Ukuxhuma amathuba nokwenziwa okuthembekile",
    xh: "Ukudibanisa amathuba nokwenziwa komsebenzi okuthembekileyo",
    zh: "将市场矿业商业机遇转化为可靠落地执行",
    ar: "ربط الفرص التجارية بتنفيذ موثوق وفعال",
    es: "Conectar oportunidades con una ejecución confiable",
    de: "Chancen mit verlässlicher Ausführung verbinden",
    hi: "अवसर को भरोसेमंद निष्पादन से जोड़ना",
    ru: "Связываем потенциальные возможности с надежным практическим исполнением",
    ja: "鉱業ビジネスの好機を信頼できる確実な実行力へと直結",
    ko: "비즈니스 기회를 신뢰할 수 있는 실행력으로 연결",
    it: "Collegare le opportunità a un'esecuzione affidabile",
    nl: "Kansen verbinden aan betrouwbare uitvoering",
  },
  "ARSSA provides focused commercial and operational support for mining-related activity across the South Africa (SADAC)–DRC corridor.": {
    en: "ARSSA provides focused commercial and operational support for mining-related activity across the South Africa (SADAC)–DRC corridor.",
    fr: "ARSSA fournit un soutien commercial et opérationnel ciblé pour les activités liées au secteur minier le long du corridor Afrique du Sud (SADAC)–RDC.",
    pt: "A ARSSA fornece apoio comercial e operacional focado para actividades relacionadas com a mineração ao longo do corredor África do Sul (SADAC)–RDC.",
    sw: "ARSSA inatoa usaidizi thabiti wa kibiashara na kiutendaji kwa shughuli zinazohusiana na madini katika korido ya Afrika Kusini (SADAC)–DRC.",
    ln: "ARSSA epesaka lisalisi ya mombo mpe ya mosala mpo na misala ya mabanga ya ntalo na nzela ya Afríka ya Súdi (SADAC)–RDC.",
    af: "ARSSA bied gefokusde kommersiële en operasionele ondersteuning vir mynbouverwante aktiwiteite oor die Suid-Afrika (SADAC)–DRK-korridor heen.",
    zu: "I-ARSSA ihlinzeka ngokusekelwa kwezohwebo nokusebenza okugxilile emisebenzini ehlobene nezimayini kulo lonke iphasishi laseNingizimu Afrika (SADAC)–DRC.",
    xh: "I-ARSSA ibonelela ngenkxaso ejolisiweyo yezorhwebo neyokusebenza kwimisebenzi enxulumene nemigodi kummandla woMzantsi Afrika (SADAC)–DRC.",
    zh: "ARSSA 为南非（SADAC）与刚果（金）跨境走廊沿线的矿业关联供应链、设备物资采购与合规协同提供高度专业化的商业及运营支持。",
    ar: "توفر ARSSA دعماً تجارياً وتشغيلياً متخصصاً للأنشطة المرتبطة بقطاع التعدين عبر ممر جنوب أفريقيا (SADAC)–جمهورية الكونغو الديمقراطية.",
    es: "ARSSA brinda soporte comercial y operativo enfocado para actividades relacionadas con la minería a lo largo del corredor Sudáfrica (SADAC)–RDC.",
    de: "ARSSA bietet zielgerichtete kommerzielle und operative Unterstützung für bergbaubezogene Aktivitäten entlang des Korridors Südafrika (SADAC)–DR Kongo.",
    hi: "ARSSA दक्षिण अफ्रीका (SADAC)-DRC गलियारे में खनन से संबंधित गतिविधियों के लिए केंद्रित वाणिज्यिक और परिचालन सहायता प्रदान करता है।",
    ru: "ARSSA оказывает целевую коммерческую и операционную поддержку предприятиям горнодобывающего сектора в коридоре Южная Африка (SADAC) — ДРК.",
    ja: "ARSSA は、南アフリカ（SADAC）〜コンゴ民主共和国回廊における鉱業関連のサプライチェーン、機材調達、パートナーシップに対し、専門的な商業・運用支援を提供します。",
    ko: "ARSSA는 남아공(SADAC)-콩고민주공화국 회랑 전반에서 광업 관련 활동을 위한 집중적인 상업 및 운영 지원을 제공합니다.",
    it: "ARSSA fornisce supporto commerciale e operativo mirato per le attività legate al settore minerario lungo il corridoio Sudafrica (SADAC)–RDC.",
    nl: "ARSSA biedt gerichte commerciële en operationele ondersteuning voor mijnbouwgerelateerde activiteiten in de corridor Zuid-Afrika (SADAC)–DRC.",
  },
  "We keep this support practical: helping identify the right partners, coordinate supply and introductions, and move opportunities toward clear next steps.": {
    en: "We keep this support practical: helping identify the right partners, coordinate supply and introductions, and move opportunities toward clear next steps.",
    fr: "Nous maintenons ce soutien pragmatique : aider à identifier les bons partenaires, coordonner l'approvisionnement et les présentations, et faire avancer les opportunités vers des étapes suivantes claires.",
    pt: "Mantemos este apoio prático: ajudando a identificar os parceiros certos, coordenar fornecimentos e apresentações, e avançar as oportunidades para próximos passos claros.",
    sw: "Tunaweka usaidizi huu kuwa wa vitendo: kusaidia kutambua washirika sahihi, kuratibu ugavi na utambulisho, na kusogeza fursa kuelekea hatua zilizo wazi zinazofuata.",
    ln: "Tosalaka mosala oyo na pambala ya solo: kosalisa kotala baninga ya malamu, kokamba kopesa biloko mpe koyebana na bato, mpe kotambwisa makambo na mikano ya polele oyo elandi.",
    af: "Ons hou hierdie ondersteuning prakties: help om die regte vennote te identifiseer, voorrade en bekendstellings te koördineer, en geleenthede na duidelike volgende stappe te beweeg.",
    zu: "Sigcina lokhu kusekelwa kusebenza: ukusiza ukuhlonza ozakwethu abafanele, ukuxhumanisa ukuhlinzekwa kanye nokwethulwa, nokuhambisa amathuba ezinyathelweni ezicacile ezilandelayo.",
    xh: "Sigcina le nkxaso isebenza ngendlela efanelekileyo: ukunceda ukuchonga amaqabane afanelekileyo, ukulungelelanisa unikezelo kunye nokwaziswa, nokuhambisa amathuba kumanyathelo acacileyo alandelayo.",
    zh: "我们始终坚持求真务实的原则：协助您精准锁定经过背景审查的合格伙伴、协调物资设备供应链与商业引荐，稳健推动矿业合作机遇迈向明确的实操阶段。",
    ar: "نحرص على أن يكون هذا الدعم عملياً: المساعدة في تحديد الشركاء المناسبين، وتنسيق التوريد والتعارف التجاري، وتحويل الفرص إلى خطوات ملموسة وواضحة.",
    es: "Mantenemos este apoyo de manera práctica: ayudando a identificar a los socios adecuados, coordinar el suministro y presentaciones, y avanzar las oportunidades hacia pasos claros.",
    de: "Wir halten diese Unterstützung praxisnah: Wir helfen dabei, die richtigen Partner zu identifizieren, Lieferketten und Geschäftskontakte zu koordinieren und Chancen in greifbare nächste Schritte umzusetzen.",
    hi: "हम इस समर्थन को व्यावहारिक रखते हैं: सही भागीदारों की पहचान करने, आपूर्ति और परिचय का समन्वय करने और अवसरों को स्पष्ट अगले कदमों की ओर ले जाने में मदद करना।",
    ru: "Мы действуем исключительно практично: помогаем подобрать надежных партнеров, организуем поставки оборудования и прямые контакты, переводя возможности в четкие проектные шаги.",
    ja: "実践的な支援に徹します。最適なビジネスパートナーの特定、資材供給と商談機会の調整、そして具体的な次のアクションへの進展を強力にサポートします。",
    ko: "우리는 실질적인 지원을 원칙으로 합니다. 적합한 파트너를 발굴하고, 공급망과 비즈니스 매칭을 조율하며, 기회를 구체적인 다음 단계로 확실히 진전시킵니다.",
    it: "Manteniamo questo supporto estremamente pratico: aiutiamo a individuare i partner giusti, coordinare le forniture e le introduzioni commerciali, guidando le opportunità verso passi successivi chiari.",
    nl: "Wij houden onze ondersteuning praktisch: we helpen de juiste partners te identificeren, leveringen en introducties te coördineren en kansen om te zetten in duidelijke vervolgstappen.",
  },

  // --- Division 05 Maintenance & Cleaning ---
  "Regulated Standards": {
    en: "Regulated Standards",
    fr: "Normes Réglementées",
    pt: "Padrões Regulamentados",
    sw: "Viwango Vinavyodhibitiwa Kisheria",
    ln: "Mibeko ya Bopeto oyo Ekatama",
    af: "Gereguleerde Standaarde",
    zu: "Amazinga Alawulwayo",
    xh: "Imigangatho Elawulwayo",
    zh: "严苛法定行业卫生规范",
    ar: "المعايير والاشتراطات التنظيمية",
    es: "Estándares Regulados",
    de: "Regulierte Standards",
    hi: "विनियमित मानक",
    ru: "Регулируемые стандарты",
    ja: "厳格な規制基準・サニタリー規格",
    ko: "법적 규제 및 위생 표준",
    it: "Standard Regolamentati",
    nl: "Gereguleerde Normen",
  },
  "Sterile & Safe Environments": {
    en: "Sterile & Safe Environments",
    fr: "Environnements Stériles et Sécurisés",
    pt: "Ambientes Estéreis e Seguros",
    sw: "Mazingira Safi na Salama",
    ln: "Bisika ya Peto mpe ya Libateli",
    af: "Steriele en Veilige Omgewings",
    zu: "Izindawo Eziyinyumba Neziphephile",
    xh: "Iindawo Ezingenazintsholongwane Nezikhuselekileyo",
    zh: "无菌安全洁净生产与作业环境",
    ar: "بيئات معقمة وآمنة تماماً",
    es: "Entornos Estériles y Seguros",
    de: "Sterile und sichere Betriebsumgebungen",
    hi: "बांझ और सुरक्षित वातावरण",
    ru: "Стерильные и безопасные условия",
    ja: "無菌で安全な運用環境",
    ko: "멸균 및 안전한 작업 환경",
    it: "Ambienti Sterili e Sicuri",
    nl: "Steriele en Veilige Omgevingen",
  },
  "Maintaining high hygiene and environmental safety protocols for regulated industries.": {
    en: "Maintaining high hygiene and environmental safety protocols for regulated industries.",
    fr: "Maintenir des protocoles stricts d'hygiène et de sécurité environnementale pour les industries réglementées.",
    pt: "Manter protocolos rigorosos de higiene e segurança ambiental para indústrias regulamentadas.",
    sw: "Kudumisha itifaki za juu za usafi na usalama wa mazingira kwa viwanda vinavyodhibitiwa kisheria.",
    ln: "Kobatela mibeko makasi ya bopeto mpe libateli ya esika mpo na ba izine oyo etosaka mibeko.",
    af: "Handhawing van hoë higiëne- en omgewingsveiligheidsprotokolle vir gereguleerde bedrywe.",
    zu: "Ukugcina izivumelwano eziphezulu zenhlanzeko nokuphepha kwendawo ezimbonini ezilawulwayo.",
    xh: "Ukugcina iinkqubo eziphezulu zococeko nezokhuseleko lokusingqongileyo kumashishini alawulwayo.",
    zh: "为医药、化工与食品等受管辖监管的重点特种行业维护最高水准的卫生消杀与环境生物安全规范。",
    ar: "الحفاظ على بروتوكولات صارمة للنظافة الصحية والسلامة البيئية للصناعات الخاضعة للرقابة.",
    es: "Mantener estrictos protocolos de higiene y seguridad ambiental para industrias reguladas.",
    de: "Einhaltung strenger Hygiene- und Umweltsicherheitsprotokolle für regulierte Industriezweige.",
    hi: "विनियमित उद्योगों के लिए उच्च स्वच्छता और पर्यावरण सुरक्षा प्रोटोकॉल बनाए रखना।",
    ru: "Поддержание строгих протоколов гигиены, дезинфекции и экологической безопасности на регулируемых производствах.",
    ja: "規制対象産業向けに、最高水準の衛生管理および環境安全プロトコルを維持・徹底します。",
    ko: "규제 대상 전문 산업군을 위해 최고 수준의 위생 및 환경 안전 관리 프로토콜을 유지합니다.",
    it: "Mantenere rigorosi protocolli di igiene e sicurezza ambientale per i settori regolamentati.",
    nl: "Het handhaven van strikte protocollen voor hygiëne en milieuveiligheid voor gereguleerde industrieën.",
  },
  "Maintaining Rigorous Operational & Sanitary Standards": {
    en: "Maintaining Rigorous Operational & Sanitary Standards",
    fr: "Maintenir des Normes Opérationnelles et Sanitaires Rigoureuses",
    pt: "Manter Normas Operacionais e Sanitárias Rigorosas",
    sw: "Kudumisha Viwango Madhubuti vya Kiutendaji na vya Afya",
    ln: "Kobatela Mibeko Makasi ya Mosala mpe ya Bokolongono",
    af: "Handhawing van Streng Operasionele en Sanitêre Standaarde",
    zu: "Ukugcina Amazinga Aqine Kakhulu Okusebenza Nawenhlanzeko",
    xh: "Ukugcina Imigangatho Engqongqo Yokusebenza Neyococeko",
    zh: "全面严密恪守高规格运营合规与卫生检疫标准",
    ar: "الحفاظ على معايير تشغيلية وصحية صارمة ودقيقة",
    es: "Mantener Rigurosos Estándares Operativos y Sanitarios",
    de: "Strenge operative und sanitäre Standards konsequent einhalten",
    hi: "कठोर परिचालन और स्वच्छता मानकों को बनाए रखना",
    ru: "Соблюдение строгих санитарно-гигиенических и производственных стандартов",
    ja: "厳格な運用水準およびサニタリー衛生基準の維持",
    ko: "엄격한 운영 및 보건 위생 기준의 철저한 준수",
    it: "Mantenere Rigorosi Standard Operativi e Sanitari",
    nl: "Het Handhaven van Strikte Operationele en Sanitaire Normen",
  },
  "Pharmaceutical laboratories, cosmetic facilities, and food-processing plants require specialised hygiene, sanitary compliance, and preventative maintenance to prevent contamination and regulatory shutdown.": {
    en: "Pharmaceutical laboratories, cosmetic facilities, and food-processing plants require specialised hygiene, sanitary compliance, and preventative maintenance to prevent contamination and regulatory shutdown.",
    fr: "Les laboratoires pharmaceutiques, les installations cosmétiques et les usines agroalimentaires nécessitent une hygiène spécialisée, une conformité sanitaire et une maintenance préventive pour éviter toute contamination et fermeture réglementaire.",
    pt: "Laboratórios farmacêuticos, instalações cosméticas e fábricas de processamento de alimentos exigem higiene especializada, conformidade sanitária e manutenção preventiva para evitar contaminação e encerramentos regulamentares.",
    sw: "Maabara ya dawa, vituo vya vipodozi, na viwanda vya kusindika chakula vinahitaji usafi maalum, uzingatiaji wa afya, na matengenezo ya kuzuia ili kuepuka uchafuzi na kufungwa na serikali.",
    ln: "Bisika ya kosala bankisi, biloko ya bopeto mpe biloko ya kolia esengaka bopeto ya sikisiki, botosi ya mibeko ya bokolongono mpe kobongisa bisaleli liboso ebeba mpo na kopekisa bosoto mpe leta akanga esika.",
    af: "Farmaseutiese laboratoriums, kosmetiese fasiliteite en voedselverwerkingsaanlegte vereis gespesialiseerde higiëne, sanitêre voldoening en voorkomende instandhouding om besmetting en regulatoriese sluiting te voorkom.",
    zu: "Amalabhorethri ezemithi, izindawo zezimonyo, nezindawo zokucubungula ukudla zidinga inhlanzeko ekhethekile, ukuhambisana nokuhlanzeka, nokugcinwa kokuvikela ukuvimbela ukungcola nokucishwa kokulawula.",
    xh: "Iilabhoratri zamayeza, amaziko ezithambiso, nezityalo zokulungisa ukutya zifuna ucoceko olukhethekileyo, ukuthotyelwa kococeko, nokulungiswa kokuthintela ukuthintela ukosuleleka nokuvalwa kolawulo.",
    zh: "制药实验室、化妆品无尘车间与食品加工厂，必须配备专门的洁净卫生管控、严格的卫生检疫合规体系及预防性设备维护，以杜绝交叉污染隐患并规避监管停产处罚。",
    ar: "تتطلب مختبرات الأدوية، ومنشآت مستحضرات التجميل، ومصانع تصنيع الأغذية نظافة متخصصة، وامتثالاً صحياً، وصيانة وقائية لمنع التلوث والإغلاق التنظيمي.",
    es: "Los laboratorios farmacéuticos, las instalaciones cosméticas y las plantas de procesamiento de alimentos requieren higiene especializada, cumplimiento sanitario y mantenimiento preventivo para evitar contaminación y clausuras regulatorias.",
    de: "Pharmazeutische Labore, Kosmetikanlagen und lebensmittelverarbeitende Betriebe erfordern spezialisierte Hygiene, sanitäre Compliance und vorbeugende Instandhaltung, um Kontaminationen und behördliche Schließungen zu verhindern.",
    hi: "फार्मास्यूटिकल प्रयोगशालाओं, कॉस्मेटिक सुविधाओं और खाद्य प्रसंस्करण संयंत्रों को संदूषण और नियामक बंद को रोकने के लिए विशेष स्वच्छता, स्वच्छता अनुपालन और निवारक रखरखाव की आवश्यकता होती है।",
    ru: "Фармацевтические лаборатории, косметические производства и пищевые комбинаты требуют специализированной гигиены, санитарного комплаенса и регулярного техобслуживания во избежание контаминации и штрафных санкций регулятора.",
    ja: "製薬研究所、化粧品製造施設、食品加工工場では、汚染リスクの防止や行政処分による操業停止を回避するため、高度な衛生管理、サニタリー適合、予防保全が強く求められます。",
    ko: "제약 연구소, 화장품 제조 시설 및 식품 가공 공장은 오염 및 규제 당국의 영업 정지 조치를 방지하기 위해 특화된 위생 관리, 보건 규정 준수 및 예방적 유지보수가 반드시 필요합니다.",
    it: "I laboratori farmaceutici, gli impianti cosmetici e gli stabilimenti di trasformazione alimentare richiedono un'igiene specializzata, conformità sanitaria e manutenzione preventiva per prevenire contaminazioni e chiusure da parte delle autorità.",
    nl: "Farmaceutische laboratoria, cosmeticafaciliteiten en voedselverwerkende fabrieken vereisen gespecialiseerde hygiëne, sanitaire naleving en preventief onderhoud om besmetting en gedwongen sluiting door toezichthouders te voorkomen.",
  },
  "ARSSA provides rigorous operational support — including medical-grade disinfection, preventative equipment maintenance, waste management, and occupational health compliance — so your facilities always pass inspection and run smoothly.": {
    en: "ARSSA provides rigorous operational support — including medical-grade disinfection, preventative equipment maintenance, waste management, and occupational health compliance — so your facilities always pass inspection and run smoothly.",
    fr: "ARSSA fournit un soutien opérationnel rigoureux — comprenant la désinfection de qualité médicale, la maintenance préventive des équipements, la gestion des déchets et la conformité à la santé au travail — afin que vos installations réussissent toujours les inspections et fonctionnent sans heurts.",
    pt: "A ARSSA fornece um apoio operacional rigoroso — incluindo desinfecção de nível médico, manutenção preventiva de equipamentos, gestão de resíduos e conformidade com a saúde no trabalho — para que as suas instalações passem sempre nas inspecções e funcionem sem problemas.",
    sw: "ARSSA inatoa usaidizi madhubuti wa kiutendaji — ikiwa ni pamoja na kuua viini kwa kiwango cha matibabu, matengenezo ya kuzuia ya vifaa, usimamizi wa taka, na kufuata afya ya kazini — ili vituo vyako vipite ukaguzi kila wakati na viendeshe vizuri.",
    ln: "ARSSA epesaka lisalisi makasi ya mosala — na peto ya monganga, kobongisa bisaleli liboso ebeba, kobwaka bosoto malamu mpe kotosa bokolongono ya basali — mpo ete bisika na yo epanza tango nyonso botali ya bakonzi mpe mosala etambola malamu.",
    af: "ARSSA bied streng operasionele ondersteuning — insluitend mediese graad ontsmetting, voorkomende toerustinginstandhouding, afvalbestuur en beroepsgesondheidsvoldoening — sodat u fasiliteite altyd inspeksie slaag en glad verloop.",
    zu: "I-ARSSA ihlinzeka ngokusekelwa kokusebenza okuqinile — okuhlanganisa ukubulala amagciwane ezingeni lezokwelapha, ukugcinwa kwemishini yokuvikela, ukuphathwa kwemfucuza, nokuhambisana nempilo yasemsebenzini — ukuze izindawo zakho zihlale ziphasa ukuhlolwa futhi zisebenze kahle.",
    xh: "I-ARSSA ibonelela ngenkxaso engqongqo yokusebenza — ebandakanya ukubulala iintsholongwane ezikumgangatho wonyango, ukulungiswa kwezixhobo zokuthintela, ulawulo lwenkunkuma, nokuthotyelwa kwempilo emsebenzini — ukuze amaziko akho ahlale ephumelela uhlolo kwaye aqhube kakuhle.",
    zh: "ARSSA 提供严密周全的现场运营保障 —— 涵盖医用级消毒杀菌、工业级设备预防性检修维护、危险废弃物合规处置及职业健康安全（OHS）达标，保障您的厂房设施从容通过官方飞行检查、常年平稳高效运行。",
    ar: "توفر ARSSA دعماً تشغيلياً صارماً — يشمل التطهير الطبي، والصيانة الوقائية للمعدات، وإدارة النفايات، والامتثال للصحة المهنية — لضمان اجتياز منشآتك لجميع عمليات التفتيش بسلاسة.",
    es: "ARSSA brinda un riguroso soporte operativo, que incluye desinfección de grado médico, mantenimiento preventivo de equipos, gestión de residuos y cumplimiento de salud ocupacional, para que sus instalaciones siempre pasen las inspecciones y funcionen sin problemas.",
    de: "ARSSA bietet präzise operative Unterstützung — einschließlich medizinischer Desinfektion, vorbeugender Wartung, Abfallmanagement und Arbeitsschutz-Compliance —, damit Ihre Anlagen jede Inspektion bestehen und reibungslos laufen.",
    hi: "ARSSA कठोर परिचालन सहायता प्रदान करता है — जिसमें मेडिकल-ग्रेड कीटाणुशोधन, निवारक उपकरण रखरखाव, अपशिष्ट प्रबंधन और व्यावसायिक स्वास्थ्य अनुपालन शामिल हैं — ताकि आपकी सुविधाएं हमेशा निरीक्षण पास करें और सुचारू रूप से चलें।",
    ru: "ARSSA обеспечивает комплексную эксплуатационную поддержку: медицинскую дезинфекцию, плановое техобслуживание, утилизацию отходов и соблюдение норм охраны труда — гарантируя успешное прохождение любых инспекций.",
    ja: "ARSSA は、医療水準の除菌消毒、設備の予防保全、廃棄物処理、労働安全衛生（OHS）コンプライアンスを含む厳格な運用サポートを提供し、貴社施設が常に査察を通過し円滑に稼働することを支援します。",
    ko: "ARSSA는 의료용 등급의 소독, 설비 예방 유지보수, 폐기물 관리 및 산업 안전 보건 준수를 포함한 철저한 현장 지원을 제공하여 귀사의 시설이 언제나 점검을 무사히 통과하고 원활히 가동되도록 보장합니다.",
    it: "ARSSA fornisce un rigoroso supporto operativo, tra cui disinfezione di grado medico, manutenzione preventiva delle apparecchiature, gestione dei rifiuti e conformità alla salute sul lavoro, affinché le tue strutture superino sempre le ispezioni e funzionino al meglio.",
    nl: "ARSSA biedt grondige operationele ondersteuning — inclusief desinfectie van medische kwaliteit, preventief onderhoud van apparatuur, afvalbeheer en naleving van de arbowetgeving — zodat uw faciliteiten altijd audits doorstaan en soepel draaien.",
  },

  // --- Form & Input Validation Messages ---
  "Please enter your name.": {
    en: "Please enter your name.",
    fr: "Veuillez entrer votre nom.",
    pt: "Por favor, insira o seu nome.",
    sw: "Tafadhali weka jina lako.",
    ln: "Tondisa kombo na yo.",
    af: "Voer asseblief u naam in.",
    zu: "Sicela ufake igama lakho.",
    xh: "Nceda ufake igama lakho.",
    zh: "请输入您的姓名。",
    ar: "يرجى إدخال اسمك.",
    es: "Por favor, ingrese su nombre.",
    de: "Bitte geben Sie Ihren Namen ein.",
    hi: "कृपया अपना नाम दर्ज करें।",
    ru: "Пожалуйста, введите ваше имя.",
    ja: "お名前を入力してください。",
    ko: "이름을 입력해 주세요.",
    it: "Inserisci il tuo nome.",
    nl: "Voer alstublieft uw naam in.",
  },
  "Please enter a valid email address.": {
    en: "Please enter a valid email address.",
    fr: "Veuillez entrer une adresse e-mail valide.",
    pt: "Por favor, insira um endereço de e-mail válido.",
    sw: "Tafadhali weka anwani halali ya barua pepe.",
    ln: "Tondisa adresi ya email ya solo.",
    af: "Voer asseblief 'n geldige e-posadres in.",
    zu: "Sicela ufake ikheli le-imeyili elivumelekile.",
    xh: "Nceda ufake idilesi ye-imeyile esemthethweni.",
    zh: "请输入有效的电子邮箱地址。",
    ar: "يرجى إدخال عنوان بريد إلكتروني صالح.",
    es: "Por favor, ingrese un correo electrónico válido.",
    de: "Bitte geben Sie eine gültige E-Mail-Adresse ein.",
    hi: "कृपया एक मान्य ईमेल पता दर्ज करें।",
    ru: "Пожалуйста, укажите действительный адрес электронной почты.",
    ja: "有効なメールアドレスを入力してください。",
    ko: "유효한 이메일 주소를 입력해 주세요.",
    it: "Inserisci un indirizzo email valido.",
    nl: "Voer alstublieft een geldig e-mailadres in.",
  },
  "Please enter a message.": {
    en: "Please enter a message.",
    fr: "Veuillez entrer un message.",
    pt: "Por favor, insira uma mensagem.",
    sw: "Tafadhali weka ujumbe.",
    ln: "Koma sango na yo.",
    af: "Voer asseblief 'n boodskap in.",
    zu: "Sicela ufake umyalezo.",
    xh: "Nceda ufake umyalezo.",
    zh: "请输入您的留言内容。",
    ar: "يرجى كتابة رسالتك.",
    es: "Por favor, ingrese un mensaje.",
    de: "Bitte geben Sie eine Nachricht ein.",
    hi: "कृपया एक संदेश दर्ज करें।",
    ru: "Пожалуйста, введите текст сообщения.",
    ja: "メッセージを入力してください。",
    ko: "메시지를 입력해 주세요.",
    it: "Inserisci un messaggio.",
    nl: "Voer alstublieft een bericht in.",
  },
  "Please enter your full name.": {
    en: "Please enter your full name.",
    fr: "Veuillez entrer votre nom complet.",
    pt: "Por favor, insira o seu nome completo.",
    sw: "Tafadhali weka jina lako kamili.",
    ln: "Tondisa kombo na yo mobimba.",
    af: "Voer asseblief u volle naam in.",
    zu: "Sicela ufake igama lakho eliphelele.",
    xh: "Nceda ufake igama lakho elipheleleyo.",
    zh: "请输入您的完整姓名。",
    ar: "يرجى إدخال اسمك الكامل.",
    es: "Por favor, ingrese su nombre completo.",
    de: "Bitte geben Sie Ihren vollständigen Namen ein.",
    hi: "कृपया अपना पूरा नाम दर्ज करें।",
    ru: "Пожалуйста, укажите ваши полные имя и фамилию.",
    ja: "フルネームをご入力ください。",
    ko: "성명을 입력해 주세요.",
    it: "Inserisci il tuo nome completo.",
    nl: "Voer alstublieft uw volledige naam in.",
  },
  "Please select the service you require.": {
    en: "Please select the service you require.",
    fr: "Veuillez sélectionner le service requis.",
    pt: "Por favor, seleccione o serviço pretendido.",
    sw: "Tafadhali chagua huduma unayohitaji.",
    ln: "Pona mosala oyo olingi.",
    af: "Kies asseblief die diens wat u benodig.",
    zu: "Sicela ukhethe isevisi oyidingayo.",
    xh: "Nceda ukhethe inkonzo oyifunayo.",
    zh: "请选择您所需的服务项目。",
    ar: "يرجى اختيار الخدمة المطلوبة.",
    es: "Por favor, seleccione el servicio requerido.",
    de: "Bitte wählen Sie die gewünschte Dienstleistung aus.",
    hi: "कृपया वह सेवा चुनें जिसकी आपको आवश्यकता है।",
    ru: "Пожалуйста, выберите интересующую вас услугу.",
    ja: "ご希望のサービスを選択してください。",
    ko: "필요하신 서비스를 선택해 주세요.",
    it: "Seleziona il servizio richiesto.",
    nl: "Selecteer alstublieft de gewenste dienst.",
  },
  "Please tell us a little about your enquiry.": {
    en: "Please tell us a little about your enquiry.",
    fr: "Veuillez préciser l'objet de votre demande.",
    pt: "Por favor, conte-nos um pouco sobre a sua consulta.",
    sw: "Tafadhali tueleze kidogo kuhusu swali lako.",
    ln: "Yebisa biso mwa moke mpo na motuna na yo.",
    af: "Vertel ons asseblief 'n bietjie oor u navraag.",
    zu: "Sicela usitshele kancane ngombuzo wakho.",
    xh: "Nceda usixelele kancinci malunga nombuzo wakho.",
    zh: "请简要描述您的业务咨询意向。",
    ar: "يرجى تزويدنا بنبذة موجزة حول استفسارك.",
    es: "Por favor, cuéntenos brevemente sobre su consulta.",
    de: "Bitte beschreiben Sie Ihr Anliegen kurz.",
    hi: "कृपया हमें अपनी पूछताछ के बारे में थोड़ा बताएं।",
    ru: "Пожалуйста, кратко опишите суть вашего запроса.",
    ja: "お問い合わせ内容の概要をご入力ください。",
    ko: "문의 내용을 간략히 기재해 주세요.",
    it: "Fornisci qualche dettaglio in merito alla tua richiesta.",
    nl: "Vertel ons alstublieft kort over uw vraag.",
  },
  "Please confirm your consent to continue.": {
    en: "Please confirm your consent to continue.",
    fr: "Veuillez confirmer votre consentement pour continuer.",
    pt: "Por favor, confirme o seu consentimento para continuar.",
    sw: "Tafadhali thibitisha idhini yako ili kuendelea.",
    ln: "Ndimisa ndingisa na yo mpo na kokoba.",
    af: "Bevestig asseblief u toestemming om voort te gaan.",
    zu: "Sicela uqinisekise imvume yakho ukuze uqhubeke.",
    xh: "Nceda uqinisekise imvume yakho ukuze uqhubeke.",
    zh: "请勾选确认同意以继续提交。",
    ar: "يرجى تأكيد موافقتك للمتابعة.",
    es: "Por favor, confirme su consentimiento para continuar.",
    de: "Bitte bestätigen Sie Ihr Einverständnis, um fortzufahren.",
    hi: "कृपया जारी रखने के लिए अपनी सहमति की पुष्टि करें।",
    ru: "Пожалуйста, подтвердите согласие для продолжения.",
    ja: "続行するには同意の確認を行ってください。",
    ko: "계속 진행하려면 동의를 확인해 주세요.",
    it: "Conferma il tuo consenso per proseguire.",
    nl: "Bevestig alstublieft uw toestemming om door te gaan.",
  },
  "Enquiry Received": {
    en: "Enquiry Received",
    fr: "Demande Reçue",
    pt: "Consulta Recebida",
    sw: "Swali Limepokelewa",
    ln: "Motuna Moyambami",
    af: "Navraag Ontvang",
    zu: "Umbuzo Wamukelwe",
    xh: "Umbuzo Ufunyenwe",
    zh: "咨询申请已成功受理",
    ar: "تم استلام استفسارك بنجاح",
    es: "Consulta Recibida",
    de: "Anfrage erhalten",
    hi: "पूछताछ प्राप्त हुई",
    ru: "Запрос успешно принят",
    ja: "お問い合わせを受け付けました",
    ko: "문의가 성공적으로 접수되었습니다",
    it: "Richiesta Ricevuta",
    nl: "Aanvraag Ontvangen",
  },
  "Thank you for contacting ARSSA. We've received your enquiry and our team will review it and respond with next steps shortly.": {
    en: "Thank you for contacting ARSSA. We've received your enquiry and our team will review it and respond with next steps shortly.",
    fr: "Merci d'avoir contacté ARSSA. Nous avons bien reçu votre demande et notre équipe l'examinera pour vous répondre dans les plus brefs délais avec les prochaines étapes.",
    pt: "Obrigado por contactar a ARSSA. Recebemos a sua consulta e a nossa equipa irá analisá-la e responder em breve com os próximos passos.",
    sw: "Asante kwa kuwasiliana na ARSSA. Tumepokea ombi lako na timu yetu italikagua na kujibu kwa hatua zinazofuata hivi karibuni.",
    ln: "Matondo mingi mpo na kobenga ARSSA. Toyambi motuna na yo mpe ekipi na biso ekotola yango mpe ekozongisela yo eyano na noki mpo na makambo oyo ekolanda.",
    af: "Dankie dat u ARSSA gekontak het. Ons het u navraag ontvang en ons span sal dit hersien en binnekort met volgende stappe reageer.",
    zu: "Siyabonga ngokuxhumana ne-ARSSA. Siwutholile umbuzo wakho futhi ithimba lethu lizowubuyekeza futhi liphendule ngezinyathelo ezilandelayo maduze.",
    xh: "Enkosi ngokuqhagamshelana ne-ARSSA. Sisiwufumene umbuzo wakho kwaye iqela lethu liza kuwuhlolisisa kwaye liphendule ngamanyathelo alandelayo kungekudala.",
    zh: "衷心感谢您垂询 ARSSA。我们已收到您的业务咨询，我们的管理团队将在短时间内完成评估并向您回复后续推进方案与详细建议。",
    ar: "شكراً لتواصلك مع ARSSA. لقد تلقينا استفسارك وسيقوم فريقنا بمراجعته والرد عليك بالخطوات التالية قريباً.",
    es: "Gracias por contactar a ARSSA. Hemos recibido su consulta y nuestro equipo la revisará para responderle pronto con los siguientes pasos.",
    de: "Vielen Dank für Ihre Kontaktaufnahme mit ARSSA. Wir haben Ihre Anfrage erhalten. Unser Team wird diese prüfen und sich in Kürze mit den nächsten Schritten bei Ihnen melden.",
    hi: "ARSSA से संपर्क करने के लिए धन्यवाद। हमें आपकी पूछताछ प्राप्त हो गई है और हमारी टीम इसकी समीक्षा करेगी और शीघ्र ही अगले कदमों के साथ जवाब देगी।",
    ru: "Благодарим за обращение в ARSSA. Ваш запрос получен, наша команда оперативно изучит его и свяжется с вами для обсуждения дальнейших шагов.",
    ja: "ARSSA へのお問い合わせありがとうございます。ご相談内容を受領いたしました。担当チームが内容を精査の上、今後の具体的な進め方について折り返しご連絡いたします。",
    ko: "ARSSA에 문의해 주셔서 감사합니다. 접수된 문의 사항을 경영진이 면밀히 검토한 후 향후 진행 절차에 대해 신속하게 안내해 드리겠습니다.",
    it: "Grazie per aver contattato ARSSA. Abbiamo ricevuto la tua richiesta; il nostro team la esaminerà e ti risponderà a breve con i passaggi successivi.",
    nl: "Hartelijk dank voor uw contact met ARSSA. We hebben uw aanvraag ontvangen en ons team zal deze beoordelen en binnenkort reageren met de vervolgstappen.",
  },
  "Full Name": {
    en: "Full Name",
    fr: "Nom Complet",
    pt: "Nome Completo",
    sw: "Jina Kamili",
    ln: "Kombo Mobimba",
    af: "Volle Naam",
    zu: "Igama Eliphelele",
    xh: "Igama Elipheleleyo",
    zh: "完整姓名",
    ar: "الاسم الكامل",
    es: "Nombre Completo",
    de: "Vollständiger Name",
    hi: "पूरा नाम",
    ru: "Полное имя",
    ja: "お名前（フルネーム）",
    ko: "성명 (전체)",
    it: "Nome Completo",
    nl: "Volledige Naam",
  },
  "Service Required": {
    en: "Service Required",
    fr: "Service Requis",
    pt: "Serviço Pretendido",
    sw: "Huduma Inayohitajika",
    ln: "Mosala oyo Esengeli",
    af: "Diens Benodig",
    zu: "Isevisi Eyidingekayo",
    xh: "Inkonzo Efunekayo",
    zh: "所需服务类别",
    ar: "الخدمة المطلوبة",
    es: "Servicio Requerido",
    de: "Gewünschte Dienstleistung",
    hi: "आवश्यक सेवा",
    ru: "Требуемая услуга",
    ja: "希望するサービス",
    ko: "필요한 서비스",
    it: "Servizio Richiesto",
    nl: "Gewenste Dienst",
  },
  "Company": {
    en: "Company",
    fr: "Entreprise",
    pt: "Empresa",
    sw: "Kampuni",
    ln: "Kompani",
    af: "Maatskappy",
    zu: "Inkampani",
    xh: "Inkampani",
    zh: "公司名称",
    ar: "الشركة",
    es: "Empresa",
    de: "Unternehmen",
    hi: "कंपनी",
    ru: "Компания",
    ja: "会社名",
    ko: "회사명",
    it: "Azienda",
    nl: "Bedrijf",
  },
  "Email address": {
    en: "Email address",
    fr: "Adresse e-mail",
    pt: "Endereço de e-mail",
    sw: "Anwani ya barua pepe",
    ln: "Adresi ya email",
    af: "E-posadres",
    zu: "Ikheli le-imeyili",
    xh: "Idilesi ye-imeyile",
    zh: "电子邮箱地址",
    ar: "عنوان البريد الإلكتروني",
    es: "Correo electrónico",
    de: "E-Mail-Adresse",
    hi: "ईमेल पता",
    ru: "Адрес электронной почты",
    ja: "メールアドレス",
    ko: "이메일 주소",
    it: "Indirizzo email",
    nl: "E-mailadres",
  },
  "Phone / WhatsApp number": {
    en: "Phone / WhatsApp number",
    fr: "Numéro de téléphone / WhatsApp",
    pt: "Número de telefone / WhatsApp",
    sw: "Nambari ya simu / WhatsApp",
    ln: "Nimero ya telefone / WhatsApp",
    af: "Telefoon / WhatsApp-nommer",
    zu: "Inombolo yocingo / WhatsApp",
    xh: "Inombolo yefowuni / WhatsApp",
    zh: "电话 / WhatsApp 号码",
    ar: "رقم الهاتف / واتساب",
    es: "Número de teléfono / WhatsApp",
    de: "Telefon- / WhatsApp-Nummer",
    hi: "फोन / व्हाट्सएप नंबर",
    ru: "Номер телефона / WhatsApp",
    ja: "電話 / WhatsApp 番号",
    ko: "전화 / WhatsApp 번호",
    it: "Numero di telefono / WhatsApp",
    nl: "Telefoon- / WhatsApp-nummer",
  },
  "Country": {
    en: "Country",
    fr: "Pays",
    pt: "País",
    sw: "Nchi",
    ln: "Mboka",
    af: "Land",
    zu: "Izwe",
    xh: "Ilizwe",
    zh: "国家 / 地区",
    ar: "الدولة",
    es: "País",
    de: "Land",
    hi: "देश",
    ru: "Страна",
    ja: "国",
    ko: "국가",
    it: "Paese",
    nl: "Land",
  },
  "Enquiry information": {
    en: "Enquiry information",
    fr: "Informations sur la demande",
    pt: "Informações sobre a consulta",
    sw: "Taarifa za swali",
    ln: "Basango ya motuna",
    af: "Navraaginligting",
    zu: "Imininingwane yombuzo",
    xh: "Iinkcukacha zombuzo",
    zh: "咨询详细内容",
    ar: "تفاصيل الاستفسار",
    es: "Información de la consulta",
    de: "Informationen zur Anfrage",
    hi: "पूछताछ की जानकारी",
    ru: "Информация по запросу",
    ja: "お問い合わせ情報",
    ko: "문의 내용",
    it: "Informazioni sulla richiesta",
    nl: "Aanvraaggegevens",
  },
};

let content = fs.readFileSync(phrasesFilePath, "utf8");
const match = content.match(/export const UNIVERSAL_PHRASES: Record<string, Partial<Record<Language, string>>> = (\{[\s\S]*\});\n$/);
if (!match) {
  console.error("Could not find UNIVERSAL_PHRASES");
  process.exit(1);
}
const existing = eval("(" + match[1] + ")");
const merged = { ...existing, ...CAT2_PHRASES };

const newPhrasesCode =
  `import type { Language } from "./languages";\n\n` +
  `export const UNIVERSAL_PHRASES: Record<string, Partial<Record<Language, string>>> = ` +
  JSON.stringify(merged, null, 2) +
  `;\n`;

fs.writeFileSync(phrasesFilePath, newPhrasesCode, "utf8");
console.log("Successfully updated universalPhrases.ts with Category 2, total keys:", Object.keys(merged).length);
